### ISSUE TITLE
Why use def instead of async def in healthcheck ?

### ISSUE THREAD

**Issue by nilansaha** [Netflix/dispatch#1073]
So, I see that you guys use `async def` in most of the functions while chose to use just `def` in the healthcheck 
```
@api_router.get("/healthcheck", include_in_schema=False)
def healthcheck():
    return {"status": "ok"}
```
This does not seem to conform with the suggestions from FastAPI doc. This is why it says in the doc.
```
If your application (somehow) doesn't have to communicate with anything else and wait for it to respond, use async def
```
[Reference](**url**)

I am just trying to understand the rationale behind this because I recently implemented healthchecks for Kubernetes in FastAPI and used `async def` and it fills my traces with this error
```
CancelledError
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/opentelemetry/trace/__init__.py", line 522, in use_span
yield span
File "/usr/local/lib/python3.7/site-packages/opentelemetry/sdk/trace/__init__.py", line 879, in start_as_current_span
yield span_context
File "/usr/local/lib/python3.7/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 213, in wrapped_receive
message = await receive()
File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 526, in receive
await self.message_event.wait()
File "/usr/local/lib/python3.7/asyncio/locks.py", line 293, in wait
await fut
concurrent.futures._base.CancelledError
```
Just trying to understand if there is a correlation or why you guys choose to use just `def`

**Comment by kevgliss** [comment]
I'm not sure I understand, we use `def` in most of our views. I believe we chose to do that with `/healthcheck` out of conformity more than anything else.  

It doesn't look like your issue isn't Dispatch specific, stackoverflow or the fastapi's gitter would probably be a better place to get a specific answer to your issue.
