### ISSUE TITLE
We're facing more issues. We have been unable to get this thing up and running in over a week.

### ISSUE THREAD

**Issue by kevgliss** [Netflix/dispatch#113]
We're facing more issues. We have been unable to get this thing up and running in over a week.

Our latest error is:

ValueError: Could not deserialize key data.
ERROR:    Unable to import dispatch.plugins.dispatch_google.groups.plugin.GoogleGroupParticipantGroupPlugin. Reason: Could not deserialize key data.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/managers.py", line 61, in all
    results.append(cls())
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/groups/plugin.py", line 122, in __init__
    self.client = get_service("admin", "directory_v1", scopes)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/common.py", line 39, in get_service
    credentials = service_account.Credentials.from_service_account_file(
  File "/usr/local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 217, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 74, in from_filename
    return data, from_dict(data, require=require)
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 55, in from_dict
    signer = crypt.RSASigner.from_service_account_info(data)
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/base.py", line 113, in from_service_account_info
    return cls.from_string(
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/_cryptography_rsa.py", line 146, in from_string
    private_key = serialization.load_pem_private_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1085, in load_pem_private_key
    return self._load_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1315, in _load_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1373, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

We're using the Google PEM file, and we've tried several variations: with new-lines, without, base64ed, etc. But we cannot launch this thing.

Can we get a full working `.env` file so we can back-trace the config from there and figure this out? The current documentation is not very helpful.

_Originally posted by @ayush-sharma in https://github.com/Netflix/dispatch/issues/55#issuecomment-599932229_

**Comment by kevgliss** [comment]
@ayush-sharma If you take a look at:

https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_google/common.py#L29

We're not doing anything particularly special with those credentials, you *should* be able to copy whatever string google gives you for a PEM and be on your way. Essentially the above code simply re-writes the google service account json file dynamically based on the config options.

**Comment by mogindi** [comment]
had the same issue. Got it working by setting it like this in .env file:

GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEv........hCK2K8g==\n-----END PRIVATE KEY-----

key points:
- no quotation marks
- pasted as one line with all the \n's
- removed last \n (not sure if that really helps, but not gonna touch it :) )

**Comment by tomarv2** [comment]
error 403:

```
web_1       | ----------------------------------
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/groups/plugin.py", line 31, in make_call
web_1       |     data = getattr(client, func)(**kwargs).execute()
web_1       |   File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
web_1       |     return wrapped(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 898, in execute
web_1       |     raise HttpError(resp, content, uri=self.uri)
web_1       | googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/admin/directory/v1/groups?key=xxxxxxxxx&alt=json returned "Not Authorized to access this resource/api">
web_1       | 
web_1       | During handling of the above exception, another exception occurred:
web_1       | 
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 394, in call
web_1       |     result = fn(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/groups/plugin.py", line 43, in make_call
web_1       |     raise TryAgain
web_1       | tenacity.TryAgain
```
