### ISSUE TITLE
AttributeError: 'Plugin' object has no attribute 'enabled'

### ISSUE THREAD

**Issue by garmstrong67** [Netflix/dispatch#1264]
1. In the Dispatch core CLI
2. Run the following command:
dispatch plugins list
3. Error appears as below:
4. 
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 706, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 69, in list_plugins
    record.enabled,
AttributeError: 'Plugin' object has no attribute 'enabled'

**Expected behavior**
Expect to see a list of the installed plugins

This is happening with all dispatch plugin commands via the CLI, and is affecting all of the plugins.  To date I have been unable to get the Slack, JIRA, or PagerDuty plugins functioning at all, although I know the config values are all correct.

**Comment by kevgliss** [comment]
Thanks for reporting, this should be fixed by #1266. Do you see any other errors? While this PR will fix the `dispatch plugins list` command it shouldn't have affected plugins generally.

**Comment by garmstrong67** [comment]
Thank you so much, this solved the issue with the dispatch plugins list command.

When attempting to create an incident now - I'm getting an error with the Slack API:

 File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/slack_response.py", line 201, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'users_not_found'}


When one part of the integrations fail, there is a failure with the entire incident creation.

**Comment by garmstrong67** [comment]
I'll close this one off as it's been fixed in #1266 - thanks!  I'll open a new issue for my other one.
