### ISSUE TITLE
Slack API Failing

### ISSUE THREAD

**Issue by garmstrong67** [Netflix/dispatch#1275]
I have the Slack configuration correctly configured as per the documentation, and the bot created and integrated with the channel.  When attempting to create an incident with slack-conversation and slack-contact enabled, I get the following failure:

  File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/slack_response.py", line 201, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'users_not_found'}

I have the following env variables correctly configured (as per the documentation) for Slack:

SLACK_API_BOT_TOKEN
DISPATCH_HELP_SLACK_CHANNEL
SLACK_SIGNING_SECRET
SLACK_SOCKET_MODE_APP_TOKEN
SLACK_APP_USER_SLUG
SLACK_WORKSPACE_NAME

However the incident does not complete creation, and the above error message appears in the logs.

I have followed the Slack configuration as described here:
https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack

**Comment by mvilanova** [comment]
@garmstrong67 can you share the full stacktrace?

**Comment by mvilanova** [comment]
This usually happens when the user email that the Slack contact plugin is trying to resolve to a Slack user id does not exist in the workspace.

**Comment by garmstrong67** [comment]
Sure:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
    await run_until_first_complete(
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
    await run_until_first_complete(
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
    await run_until_first_complete(
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/views.py", line 105, in create_incident
    incident = create(
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/service.py", line 230, in create
    assign_incident_role(db_session, incident, reporter_email, ParticipantRoleType.reporter)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/service.py", line 61, in assign_incident_role
    participant_flows.add_participant(
  File "/usr/local/lib/python3.8/site-packages/dispatch/participant/flows.py", line 27, in add_participant
    individual = individual_service.get_or_create(
  File "/usr/local/lib/python3.8/site-packages/dispatch/individual/service.py", line 55, in get_or_create
    individual_info = contact_plugin.instance.get(email, db_session=db_session)
  File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 58, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/plugin.py", line 208, in get
    profile = get_user_profile_by_email(self.client, email)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 199, in get_user_profile_by_email
    user = make_call(client, "users.lookupByEmail", email=email)["user"]
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 339, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 430, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 367, in iter
    return fut.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 139, in make_call
    raise e
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 113, in make_call
    response = client.api_call(endpoint, http_verb="GET", params=kwargs)
  File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 135, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 171, in _sync_send
    return self._urllib_api_call(
  File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 303, in _urllib_api_call
    return SlackResponse(
  File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/slack_response.py", line 201, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'users_not_found'}


Can you elaborate a little more on that?   For SLACK_APP_USER_SLUG I'm using the U* ID of the bot used for Dispatch.  Should I be specifying this within the UI somewhere too?

Thank you for your response!

**Comment by kevgliss** [comment]
Judging from the stack trace, what email you have specified for `reporter_email` (e.g. the logged in user that is reporting the incident) isn't a member of the slack workspace you have configured.

**Comment by mvilanova** [comment]
No, you don't need to specify the SLACK_APP_USER_SLUG in the UI, only in the .env file. We use it to avoid processing events generated by the bot in the incident channel (e.g. bot posting a message).

**Comment by garmstrong67** [comment]
Thanks - I think I solved the issue with the user - now getting this:

ERROR:dispatch.decorators:'NoneType' object has no attribute 'channel_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 37, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 728, in incident_create_flow
    send_incident_participant_announcement_message(user_email, incident, db_session)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/messaging.py", line 458, in send_incident_participant_announcement_message
    incident.conversation.channel_id,
AttributeError: 'NoneType' object has no attribute 'channel_id'


I have the Slack channel configured in Notifications under Target - am I missing it elsewhere?

Thanks again for your help on this.

**Comment by mvilanova** [comment]
Based on the error, it appears that the conversation object did not get created and Dispatch is complaining when it tries to access the channel_id attribute.

Were there any other errors when the incident was created?

**Comment by mvilanova** [comment]
It has nothing to do with Notifications in this case.

**Comment by garmstrong67** [comment]
Sorry for the delay - I was away for a few days.

No other errors when the incident is created, just the above.  Where should the channel_id be defined?  I have the DISPATCH_HELP_SLACK_CHANNEL envvar set to the channel name, should this perhaps be the alphanumeric channel ID?

**Comment by kevgliss** [comment]
No worries, the channel_id here is dynamic, meaning that it will be the channel_id of the channel created specifically for this incident. 

When the incident resources are created, do you see a slack channel being created?

**Comment by garmstrong67** [comment]
No, no channel is created unfortunately.  I have configured the slack bot with the correct scopes as detailed in the documentation, it's correctly installed, and the slack process is running on the server via 'dispatch server slack' (it's running in socket mode).  When creating a new incident the 'Creating incident conversation' under 'Incident Resources' never completes, and here is the stack trace:

INFO:     10.193.33.48:33186 - "POST /api/v1/default/incidents HTTP/1.1" 200 OK
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: ticket ProjectId: 1
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: participant ProjectId: 1
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: participant-group ProjectId: 1
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: storage ProjectId: 1
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: conference ProjectId: 1
ERROR:dispatch.incident.flows:'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 652, in incident_create_flow
    conversation = create_conversation(incident, db_session)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 369, in create_conversation
    conversation = plugin.instance.create(incident.name)
  File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 58, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/plugin.py", line 91, in create
    return create_conversation(self.client, name, is_private)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 287, in create_conversation
    name=name.lower(),  # slack disallows upperCase
AttributeError: 'NoneType' object has no attribute 'lower'
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: ticket ProjectId: 1
WARNING:dispatch.incident.flows:External ticket not updated, no ticket plugin enabled.
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: document ProjectId: 1
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: participant-group ProjectId: 1
ERROR:dispatch.incident.flows:'NoneType' object has no attribute 'channel_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 419, in add_participants_to_conversation
    plugin.instance.add(incident.conversation.channel_id, participant_emails)
AttributeError: 'NoneType' object has no attribute 'channel_id'
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: contact ProjectId: 1
ERROR:dispatch.decorators:'NoneType' object has no attribute 'channel_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 37, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 728, in incident_create_flow
    send_incident_participant_announcement_message(user_email, incident, db_session)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/messaging.py", line 458, in send_incident_participant_announcement_message
    incident.conversation.channel_id,
AttributeError: 'NoneType' object has no attribute 'channel_id'

I fear I'm missing some configuration somewhere, at this stage it doesn't feel like a bug.

**Comment by garmstrong67** [comment]
Closing, configuration issue
