### ISSUE TITLE
Errors with Tasks View

### ISSUE THREAD

**Issue by cl-ericz** [Netflix/dispatch#1333]
**Describe the bug**
"Something has gone very wrong" error when opening Tasks view.

**To Reproduce**
1. Go to Tasks menu

**Expected behavior**
Tasks load (?). I am unclear exactly how this functionality works, does it show an overview of tasks created via gdocs integration? Or only tasks created via the UI? Creating tasks via gdocs comments works as expected (i.e. posted to slack + incident timeline in UI).

**Desktop (please complete the following information):**
 - macOS, Chrome v91

Guessing I will need to add some additional logging statements to make the underlying error more obvious, if you can point me in the right direction I can dig further.

Viewing Task errors:
```
web_1        | 2021-06-18T00:49:58.402903220Z INFO:ROLLBACK:/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py:_rollback_impl:747
web_1        | 2021-06-18T00:49:58.403729549Z INFO:     192.168.32.1:46156 - "GET /api/v1/default/tasks?q=&page=1&itemsPerPage=10&sortBy[]=status&descending[]=false HTTP/1.0" 500 Internal Server Error
web_1        | 2021-06-18T00:49:58.404818386Z ERROR:    Exception in ASGI application
web_1        | 2021-06-18T00:49:58.404836516Z Traceback (most recent call last):
web_1        | 2021-06-18T00:49:58.404842573Z   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
web_1        | 2021-06-18T00:49:58.404847702Z     result = await app(self.scope, self.receive, self.send)
web_1        | 2021-06-18T00:49:58.404852515Z   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
web_1        | 2021-06-18T00:49:58.404857387Z     return await self.app(scope, receive, send)
web_1        | 2021-06-18T00:49:58.404862163Z   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
web_1        | 2021-06-18T00:49:58.404867011Z     await self.middleware_stack(scope, receive, send)
web_1        | 2021-06-18T00:49:58.404871883Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        | 2021-06-18T00:49:58.404876621Z     raise exc from None
web_1        | 2021-06-18T00:49:58.404881179Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        | 2021-06-18T00:49:58.404885889Z     await self.app(scope, receive, _send)
web_1        | 2021-06-18T00:49:58.404897809Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        | 2021-06-18T00:49:58.404902824Z     await response(scope, receive, send)
web_1        | 2021-06-18T00:49:58.404907433Z   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 224, in __call__
web_1        | 2021-06-18T00:49:58.404912217Z     await run_until_first_complete(
web_1        | 2021-06-18T00:49:58.404916897Z   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
web_1        | 2021-06-18T00:49:58.404921722Z     [task.result() for task in done]
web_1        | 2021-06-18T00:49:58.404926382Z   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in <listcomp>
web_1        | 2021-06-18T00:49:58.404931548Z     [task.result() for task in done]
web_1        | 2021-06-18T00:49:58.404936216Z   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 216, in stream_response
web_1        | 2021-06-18T00:49:58.404941140Z     async for chunk in self.body_iterator:
web_1        | 2021-06-18T00:49:58.404945905Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        | 2021-06-18T00:49:58.404950791Z     task.result()
web_1        | 2021-06-18T00:49:58.404955537Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        | 2021-06-18T00:49:58.404960319Z     await self.app(scope, receive, send)
web_1        | 2021-06-18T00:49:58.404964869Z   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
web_1        | 2021-06-18T00:49:58.404969589Z     raise exc from None
web_1        | 2021-06-18T00:49:58.404974266Z   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
web_1        | 2021-06-18T00:49:58.404979095Z     await self.app(scope, receive, send)
web_1        | 2021-06-18T00:49:58.404984583Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        | 2021-06-18T00:49:58.404989472Z     await response(scope, receive, send)
web_1        | 2021-06-18T00:49:58.404994097Z   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 224, in __call__
web_1        | 2021-06-18T00:49:58.404998872Z     await run_until_first_complete(
web_1        | 2021-06-18T00:49:58.405003513Z   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
web_1        | 2021-06-18T00:49:58.405008274Z     [task.result() for task in done]
web_1        | 2021-06-18T00:49:58.405012976Z   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in <listcomp>
web_1        | 2021-06-18T00:49:58.405017856Z     [task.result() for task in done]
web_1        | 2021-06-18T00:49:58.405022474Z   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 216, in stream_response
web_1        | 2021-06-18T00:49:58.405027269Z     async for chunk in self.body_iterator:
web_1        | 2021-06-18T00:49:58.405031897Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        | 2021-06-18T00:49:58.405040187Z     task.result()
web_1        | 2021-06-18T00:49:58.405048768Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        | 2021-06-18T00:49:58.405053878Z     await self.app(scope, receive, send)
web_1        | 2021-06-18T00:49:58.405058488Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        | 2021-06-18T00:49:58.405063224Z     await response(scope, receive, send)
web_1        | 2021-06-18T00:49:58.405067812Z   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 224, in __call__
web_1        | 2021-06-18T00:49:58.405072756Z     await run_until_first_complete(
web_1        | 2021-06-18T00:49:58.405077574Z   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
web_1        | 2021-06-18T00:49:58.405082396Z     [task.result() for task in done]
web_1        | 2021-06-18T00:49:58.405086990Z   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in <listcomp>
web_1        | 2021-06-18T00:49:58.405091787Z     [task.result() for task in done]
web_1        | 2021-06-18T00:49:58.405096389Z   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 216, in stream_response
web_1        | 2021-06-18T00:49:58.405101142Z     async for chunk in self.body_iterator:
web_1        | 2021-06-18T00:49:58.405105816Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        | 2021-06-18T00:49:58.405110610Z     task.result()
web_1        | 2021-06-18T00:49:58.405115125Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        | 2021-06-18T00:49:58.405119881Z     await self.app(scope, receive, send)
web_1        | 2021-06-18T00:49:58.405124537Z   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        | 2021-06-18T00:49:58.405129305Z     raise exc from None
web_1        | 2021-06-18T00:49:58.405134242Z   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        | 2021-06-18T00:49:58.405139126Z     await self.app(scope, receive, sender)
web_1        | 2021-06-18T00:49:58.405143861Z   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
web_1        | 2021-06-18T00:49:58.405148608Z     await route.handle(scope, receive, send)
web_1        | 2021-06-18T00:49:58.405153205Z   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 390, in handle
web_1        | 2021-06-18T00:49:58.405157902Z     await self.app(scope, receive, send)
web_1        | 2021-06-18T00:49:58.405162495Z   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
web_1        | 2021-06-18T00:49:58.405167252Z     await super().__call__(scope, receive, send)
web_1        | 2021-06-18T00:49:58.405171892Z   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
web_1        | 2021-06-18T00:49:58.405176624Z     await self.middleware_stack(scope, receive, send)
web_1        | 2021-06-18T00:49:58.405181258Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        | 2021-06-18T00:49:58.405189063Z     raise exc from None
web_1        | 2021-06-18T00:49:58.405193695Z   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        | 2021-06-18T00:49:58.405198604Z     await self.app(scope, receive, _send)
web_1        | 2021-06-18T00:49:58.405203347Z   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        | 2021-06-18T00:49:58.405208221Z     raise exc from None
web_1        | 2021-06-18T00:49:58.405212896Z   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        | 2021-06-18T00:49:58.405217646Z     await self.app(scope, receive, sender)
web_1        | 2021-06-18T00:49:58.405222235Z   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
web_1        | 2021-06-18T00:49:58.405226944Z     await route.handle(scope, receive, send)
web_1        | 2021-06-18T00:49:58.405231557Z   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
web_1        | 2021-06-18T00:49:58.405236274Z     await self.app(scope, receive, send)
web_1        | 2021-06-18T00:49:58.405240861Z   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
web_1        | 2021-06-18T00:49:58.405245598Z     response = await func(request)
web_1        | 2021-06-18T00:49:58.405250167Z   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
web_1        | 2021-06-18T00:49:58.405254873Z     raw_response = await run_endpoint_function(
web_1        | 2021-06-18T00:49:58.405259487Z   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
web_1        | 2021-06-18T00:49:58.405264270Z     return await run_in_threadpool(dependant.call, **values)
web_1        | 2021-06-18T00:49:58.405268902Z   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
web_1        | 2021-06-18T00:49:58.405273684Z     return await loop.run_in_executor(None, func, *args)
web_1        | 2021-06-18T00:49:58.405278781Z   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
web_1        | 2021-06-18T00:49:58.405283578Z     result = self.fn(*self.args, **self.kwargs)
web_1        | 2021-06-18T00:49:58.405288176Z   File "/usr/local/lib/python3.8/site-packages/dispatch/task/views.py", line 41, in get_tasks
web_1        | 2021-06-18T00:49:58.405292965Z     return TaskPagination(**pagination).dict()
web_1        | 2021-06-18T00:49:58.405297580Z   File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
web_1        | 2021-06-18T00:49:58.405302376Z pydantic.error_wrappers.ValidationError: 2 validation errors for TaskPagination
web_1        | 2021-06-18T00:49:58.405307107Z items -> 0 -> weblink
web_1        | 2021-06-18T00:49:58.405311837Z   expected string or bytes-like object (type=type_error)
web_1        | 2021-06-18T00:49:58.405316451Z items -> 2 -> weblink
web_1        | 2021-06-18T00:49:58.405321208Z   expected string or bytes-like object (type=type_error)
```

Creating a task (from the UI), mostly the same backtrace as above:
```
web_1        | 2021-06-18T00:51:52.418324846Z pydantic.error_wrappers.ValidationError: 1 validation error for TaskRead
web_1        | 2021-06-18T00:51:52.418329635Z response -> weblink
web_1        | 2021-06-18T00:51:52.418334333Z   expected string or bytes-like object (type=type_error)
```

**Comment by kevgliss** [comment]
Thanks for reporting, this should be fixed by #1362
