### ISSUE TITLE
Running dispatch locally

### ISSUE THREAD

**Issue by sumansid** [Netflix/dispatch#1538]
@kevgliss I'm trying to run the dispatch project locally (without Docker)

I did the following : 
```
git clone git@github.com:Netflix/dispatch.git
```
```
cd dispatch
```
```
pip3 install . 
```

May I know how I could run the dispatch server ?

**Comment by kevgliss** [comment]
The command is `dispatch server develop`. 

See: https://hawkins.gitbook.io/dispatch/administration-guide/cli

**Comment by sumansid** [comment]
Getting the following error message when I run  `dispatch server develop`. I also checked in the .env file for the necessary keys. 

`No JWT secret specified, this is required if you are using basic authentication.
No JWT secret specified, this is required if you are using basic authentication.
Traceback (most recent call last):
  File "/Users/Library/Python/3.8/bin/dispatch", line 5, in <module>
    from dispatch.cli import entrypoint
  File "/Users/Library/Python/3.8/lib/python/site-packages/dispatch/cli.py", line 14, in <module>
    from dispatch import __version__, config
  File "/Users/Library/Python/3.8/lib/python/site-packages/dispatch/config.py", line 164, in <module>
    DATABASE_HOSTNAME = config("DATABASE_HOSTNAME")
  File "/Users/Library/Python/3.8/lib/python/site-packages/starlette/config.py", line 64, in __call__
    return self.get(key, cast, default)
  File "/UsersLibrary/Python/3.8/lib/python/site-packages/starlette/config.py", line 77, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'DATABASE_HOSTNAME' is missing, and has no default."`

**Comment by kevgliss** [comment]
By default, dispatch will look for its variables in your shell's envvars or in a file is named `.env` in your current working directory. When you run any dispatch command one of those must be available.

**Comment by sumansid** [comment]
Thanks !
