### ISSUE TITLE
/dispatch-report-incident slack command fails

### ISSUE THREAD

**Issue by mnuck-fp** [Netflix/dispatch#1635]
**Describe the bug**
`/dispatch-report-incident` dies when trying to find the `slack-contact` plugin and fails to completely construct an incident record.

**To Reproduce**
1. In a slack channel with the app invited, type `/dispatch-report-incident`
2. Work through the form.
3. See the following in slack:
<img width="957" alt="Screen Shot 2021-09-21 at 9 45 58 PM" src="https://user-images.githubusercontent.com/74422539/134284948-f7db96c2-e24e-4a55-9613-48d44176eb9a.png">
4. See the following partially constructed incident in the Dispatch UI:
<img width="1140" alt="Screen Shot 2021-09-21 at 9 48 12 PM" src="https://user-images.githubusercontent.com/74422539/134285101-a49e845c-946d-48eb-aa85-db30824a3b67.png">
5. See the following in the logs from the slack container:

```
slack_1      | 2021-09-22T03:49:52.328560715Z INFO:Dispatch Core App: Incident created:/usr/local/lib/python3.9/site-packages/dispatch/event/service.py:log:100
slack_1      | 2021-09-22T03:49:52.344236073Z ERROR:Unable to find slug: slack-contact in self.all version 1: <generator object PluginManager.all at 0x7f04aabc5190> or version 2: <generator object PluginManager.all at 0x7f04aabc5190>:/usr/local/lib/python3.9/site-packages/dispatch/plugins/bas
e/manager.py:get:38
slack_1      | 2021-09-22T03:49:52.345427196Z ERROR:'slack-contact':/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/decorators.py:wrapper:159
slack_1      | 2021-09-22T03:49:52.345462820Z Traceback (most recent call last):
slack_1      | 2021-09-22T03:49:52.345469157Z   File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/decorators.py", line 133, in wrapper
slack_1      | 2021-09-22T03:49:52.345475000Z     result = func(*args, **kwargs)
slack_1      | 2021-09-22T03:49:52.345479670Z   File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/modals/incident/handlers.py", line 137, in report_incident_from_submitted_form
slack_1      | 2021-09-22T03:49:52.345485127Z     incident = incident_service.create(db_session=db_session, incident_in=incident_in)
slack_1      | 2021-09-22T03:49:52.345489565Z   File "/usr/local/lib/python3.9/site-packages/dispatch/incident/service.py", line 190, in create
slack_1      | 2021-09-22T03:49:52.345495001Z     assign_incident_role(
slack_1      | 2021-09-22T03:49:52.345499314Z   File "/usr/local/lib/python3.9/site-packages/dispatch/incident/service.py", line 60, in assign_incident_role
slack_1      | 2021-09-22T03:49:52.345502501Z     participant_flows.add_participant(
slack_1      | 2021-09-22T03:49:52.345505424Z   File "/usr/local/lib/python3.9/site-packages/dispatch/participant/flows.py", line 26, in add_participant
slack_1      | 2021-09-22T03:49:52.345508501Z     individual = individual_service.get_or_create(
slack_1      | 2021-09-22T03:49:52.345511366Z   File "/usr/local/lib/python3.9/site-packages/dispatch/individual/service.py", line 92, in get_or_create
slack_1      | 2021-09-22T03:49:52.345514434Z     individual_info = contact_plugin.instance.get(email, db_session=db_session)
slack_1      | 2021-09-22T03:49:52.345517463Z   File "/usr/local/lib/python3.9/site-packages/dispatch/plugin/models.py", line 53, in instance
slack_1      | 2021-09-22T03:49:52.345521318Z     return plugins.get(self.plugin.slug)
slack_1      | 2021-09-22T03:49:52.345525520Z   File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/base/manager.py", line 41, in get
slack_1      | 2021-09-22T03:49:52.345529800Z     raise KeyError(slug)
slack_1      | 2021-09-22T03:49:52.345533087Z KeyError: 'slack-contact'
slack_1      | 2021-09-22T03:49:52.345677353Z DEBUG:Sending a request - url: https://www.slack.com/api/chat.postEphemeral, query_params: {}, body_params: {}, files: {}, json_body: {'channel': 'C011BMZRDE3', 'user': 'ULN2K4EG5', 'text': "Sorry, we've run into an unexpected error. For help plea
se reach out to your Dispatch admins and provide them with the following token: 'f4418659-edf4-4eac-9828-85206a1b9895'.", 'blocks': None}, headers: {'Content-Type': 'application/json;charset=utf-8', 'Authorization': '(redacted)', 'User-Agent': 'Python/3.9.7 slackclient/3.10.1 Linux/5.4.0-1029
-aws'}:/usr/local/lib/python3.9/site-packages/slack_sdk/web/base_client.py:_urllib_api_call:252
slack_1      | 2021-09-22T03:49:52.408948536Z DEBUG:Received the following response - status: 200, headers: {'date': 'Wed, 22 Sep 2021 03:49:52 GMT', 'server': 'Apache', 'x-xss-protection': '0', 'pragma': 'no-cache', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'access-con
trol-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-slack-req-id': '7aff0a877ae8dd433c0efed998fd4e75', 'x-content-type-options': 'nosniff', 'referrer-policy': 'no-referrer', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'x
-slack-backend': 'r', 'x-oauth-scopes': 'channels:read,commands,groups:history,groups:read,chat:write,files:read,groups:write,im:history,im:read,im:write,mpim:history,mpim:read,mpim:write,pins:write,reactions:read,reactions:write,reminders:write,remote_files:read,team:read,users:read,users:re
ad.email,users.profile:read,users:write', 'x-accepted-oauth-scopes': 'chat:write', 'expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'vary': 'Accept-Encoding', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags',
'content-type': 'application/json; charset=utf-8', 'x-envoy-upstream-service-time': '48', 'x-backend': 'main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow', 'x-server': 'slack-
www-hhvm-main-iad-67a6', 'x-via': 'envoy-www-iad-uiwe, haproxy-edge-iad-wubh', 'x-slack-shared-secret-outcome': 'shared-secret', 'via': 'envoy-www-iad-uiwe', 'connection': 'close', 'transfer-encoding': 'chunked'}, body: {"ok":true,"message_ts":"1632282592.007300"}:/usr/local/lib/python3.9/sit
e-packages/slack_sdk/web/base_client.py:_perform_urllib_http_request_internal:537
slack_1      | 2021-09-22T03:49:52.410218978Z DEBUG:Message processing completed (type: interactive, envelope_id: e05b5e8c-c2c9-4011-9c72-6a281e7caad9):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/async_client.py:run_message_listeners:153
```

**Expected behavior**
An incident should be fully constructed, behaving the same way as an incident created from the dispatch UI.

**Additional context**
We are running `v20210913` (current latest) plus https://github.com/Netflix/dispatch/pull/1617. I haven't tried HEAD yet.

Incidents can be created from the Dispatch UI.

docker-compose.yml stanza for the slack container:
```
  slack:
    <<: *restart_policy
    image: dispatch-local
    depends_on:
#      - postgres
      - core
    env_file:
      - .env
    command: ["server", "slack"]
```
the DB is running as an external RDS instance, hence commented out the dependency on the postgres container.

As far as I can tell, the `slack-contact` plugin is installed and enabled.
<img width="1149" alt="Screen Shot 2021-09-21 at 9 58 20 PM" src="https://user-images.githubusercontent.com/74422539/134285898-49a28ac0-8b57-4d9a-8edc-a99c916746af.png">

**Comment by kevgliss** [comment]
Thanks for the detailed report, could you provide any errors on server startup? When the server starts it tries to load all the plugins, if it can't it should give us a decent error.

**Comment by mnuck-fp** [comment]
Slack container startup log:
```
2021-09-23T18:59:04.534670019Z No JWT Email Override specified. 'email' is expected in the idtoken.
2021-09-23T18:59:05.280293806Z INFO:No metric providers defined via METRIC_PROVIDERS env var. Metrics will not be sent.:/usr/local/lib/python3.9/site-packages/dispatch/metrics.py:__init__:15
2021-09-23T18:59:05.852260030Z DEBUG:Using selector: EpollSelector:/usr/local/lib/python3.9/asyncio/selector_events.py:__init__:59
2021-09-23T18:59:05.857547220Z DEBUG:Sending a request - url: POST https://www.slack.com/api/apps.connections.open, params: {}, files: {}, data: {}, json: {}, proxy: {}, headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': '(redacted)', 'User-Agent': 'Python/3.9.7 slackclient/3.10.1 Linux/5.4.0-1029-aws'}:/usr/local/lib/python3.9/site-packages/slack_sdk/web/async_internal_utils.py:_request_with_session:102
2021-09-23T18:59:05.894867251Z DEBUG:Received the following response - status: 200, headers: {'Date': 'Thu, 23 Sep 2021 18:59:05 GMT', 'Server': 'Apache', 'Access-Control-Expose-Headers': 'x-slack-req-id, retry-after', 'Access-Control-Allow-Headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'Access-Control-Allow-Origin': '*', 'x-slack-backend': 'r', 'x-oauth-scopes': 'connections:write', 'x-xss-protection': '0', 'x-slack-req-id': 'f5d296db0d0da2370734b97a3ceb9e84', 'referrer-policy': 'no-referrer', 'x-content-type-options': 'nosniff', 'Vary': 'Accept-Encoding', 'x-accepted-oauth-scopes': 'connections:write', 'Content-Encoding': 'gzip', 'Content-Length': '165', 'Content-Type': 'application/json; charset=utf-8', 'x-envoy-upstream-service-time': '20', 'x-backend': 'main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-mfhf', 'x-via': 'envoy-www-iad-4uom, haproxy-edge-iad-fii1', 'x-slack-shared-secret-outcome': 'shared-secret', 'Via': 'envoy-www-iad-4uom'}, body: {'ok': True, 'url': 'wss://wss-primary.slack.com/link/?ticket=(redacted)&app_id=(redacted)'}:/usr/local/lib/python3.9/site-packages/slack_sdk/web/async_internal_utils.py:_request_with_session:148
2021-09-23T18:59:05.910061774Z INFO:A new session has been established:/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:connect:207
2021-09-23T18:59:05.944867183Z DEBUG:Received message (type: TEXT, data: {"type":"hello","num_connections":2,"debug_info":{"host":"applink-85bd844884-79wdt","build_number":2,"approximate_connection_time":18060},"connection_info":{"app_id":"(redacted, looks correct)"}}, extra: ):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:156
2021-09-23T18:59:05.944899105Z DEBUG:A new message enqueued (current queue size: 1):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/async_client.py:enqueue_message:101
2021-09-23T18:59:05.945068246Z DEBUG:Message processing started (type: hello, envelope_id: None):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/async_client.py:run_message_listeners:125
2021-09-23T18:59:05.945160818Z DEBUG:Message processing completed (type: hello, envelope_id: None):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/async_client.py:run_message_listeners:153
```

web container startup log
```
2021-09-23T19:02:35.553895484Z No JWT Email Override specified. 'email' is expected in the idtoken.
2021-09-23T19:02:36.098975719Z DEBUG:Using selector: EpollSelector:/usr/local/lib/python3.9/asyncio/selector_events.py:__init__:59
2021-09-23T19:02:36.447359509Z INFO:No metric providers defined via METRIC_PROVIDERS env var. Metrics will not be sent.:/usr/local/lib/python3.9/site-packages/dispatch/metrics.py:__init__:15
2021-09-23T19:02:40.429806032Z DEBUG:Configuring extensions...:/usr/local/lib/python3.9/site-packages/dispatch/extensions.py:configure_extensions:25
2021-09-23T19:02:40.444375434Z DEBUG:Using the following tags... ENV_TAGS: {}:/usr/local/lib/python3.9/site-packages/dispatch/extensions.py:configure_extensions:43
2021-09-23T19:02:40.453244293Z INFO:Attempting to load plugin: dispatch_basic_auth:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.059162532Z INFO:Successfully loaded plugin: dispatch_basic_auth:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.059235926Z INFO:Attempting to load plugin: dispatch_contact:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.083644573Z INFO:Successfully loaded plugin: dispatch_contact:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.083721936Z INFO:Attempting to load plugin: dispatch_document_resolver:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.107694437Z INFO:Successfully loaded plugin: dispatch_document_resolver:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.107839325Z INFO:Attempting to load plugin: dispatch_participant_resolver:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.131003480Z INFO:Successfully loaded plugin: dispatch_participant_resolver:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.131107444Z INFO:Attempting to load plugin: dispatch_pkce_auth:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.155224791Z INFO:Successfully loaded plugin: dispatch_pkce_auth:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.155292434Z INFO:Attempting to load plugin: dispatch_ticket:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.179366654Z INFO:Successfully loaded plugin: dispatch_ticket:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.179432032Z INFO:Attempting to load plugin: google_calendar_conference:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.311143933Z INFO:Successfully loaded plugin: google_calendar_conference:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.311249443Z INFO:Attempting to load plugin: google_docs_document:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.337446300Z INFO:Successfully loaded plugin: google_docs_document:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.337521490Z INFO:Attempting to load plugin: google_drive_storage:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.382273796Z INFO:Successfully loaded plugin: google_drive_storage:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.382335008Z INFO:Attempting to load plugin: google_drive_task:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.406060094Z INFO:Successfully loaded plugin: google_drive_task:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.406157378Z INFO:Attempting to load plugin: google_gmail_email:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.431594365Z INFO:Successfully loaded plugin: google_gmail_email:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.431683623Z INFO:Attempting to load plugin: google_groups_participants:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.455447462Z INFO:Successfully loaded plugin: google_groups_participants:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.455527436Z INFO:Attempting to load plugin: jira_ticket:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.485357105Z INFO:Successfully loaded plugin: jira_ticket:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.485408189Z INFO:Attempting to load plugin: opsgenie_oncall:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.509907152Z INFO:Failed to load plugin opsgenie_oncall due to missing configuration items. "Config 'OPSGENIE_API_KEY' is missing, and has no default.":/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:38
2021-09-23T19:02:41.509979505Z INFO:Attempting to load plugin: pagerduty_oncall:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:41.535152560Z INFO:Successfully loaded plugin: pagerduty_oncall:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:41.535222761Z INFO:Attempting to load plugin: slack_contact:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:42.068643873Z INFO:Successfully loaded plugin: slack_contact:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:42.068718703Z INFO:Attempting to load plugin: slack_conversation:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:42.092816753Z INFO:Successfully loaded plugin: slack_conversation:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:31
2021-09-23T19:02:42.092870065Z INFO:Attempting to load plugin: zoom_conference:/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:27
2021-09-23T19:02:42.121667893Z INFO:Failed to load plugin zoom_conference due to missing configuration items. "Config 'ZOOM_API_USER_ID' is missing, and has no default.":/usr/local/lib/python3.9/site-packages/dispatch/common/utils/cli.py:install_plugins:38
2021-09-23T19:02:43.808716566Z INFO:     Started server process [1]
2021-09-23T19:02:43.808759320Z INFO:Started server process [1]:/usr/local/lib/python3.9/site-packages/uvicorn/server.py:serve:84
2021-09-23T19:02:43.808849714Z INFO:     Waiting for application startup.
2021-09-23T19:02:43.808863258Z INFO:Waiting for application startup.:/usr/local/lib/python3.9/site-packages/uvicorn/lifespan/on.py:startup:45
2021-09-23T19:02:43.809162616Z INFO:     Application startup complete.
2021-09-23T19:02:43.809194974Z INFO:Application startup complete.:/usr/local/lib/python3.9/site-packages/uvicorn/lifespan/on.py:startup:59
2021-09-23T19:02:43.809766307Z INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2021-09-23T19:02:43.809784983Z INFO:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit):/usr/local/lib/python3.9/site-packages/uvicorn/server.py:_log_started_message:217
```

It looks to me like the slack container isn't even trying to load plugins.

**Comment by kevgliss** [comment]
Ah, I see the issue:

Your version is missing this line: 
https://github.com/Netflix/dispatch/pull/1598/files#diff-b0d7a6fe8958049cdf1fbf6bdc0ef6aed6592c7ac1ffc8c69542f4c20a928902R723

This was only recently fixed and has not yet been released.

**Comment by mnuck-fp** [comment]
This did fix the issue, thank you!
