### ISSUE TITLE
Opsgenie module is always picking schedule defined in .env

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#1653]
Once the opsgenie plugin is enabled, it picks Incident commander role from the schedule defined in the .env file under 'OPSGENIE_TEAM_ID' config. 
Even if we add different opsgenie services (settings > project > contact > Services) with different schedule IDs or external ids, it picks up the incident commander role from the schedule defined in the .env file

**To Reproduce**
1. Run dispatch-docker environment, with OPSGENIE_API_KEY and 'OPSGENIE_TEAM_ID' config. 
2. Enable opsgenie plugin from settings
3. Create new 'Services' selecting opsgenie-oncall plugin with a different schedule ID configured in .env file.
4. In 'Incident Types' specify the confgured on-call service created in Step 3
5. Report a new incident, selecting the service type modified in step 4

**Expected behavior**
When the incident is created, its Incident Commander, should be from the service (opsgenie schedule) defined in step 3.
However, it picks Incident commander role from the schedule defined in the .env file

**Comment by kevgliss** [comment]
Yes, I noticed this during some other refactoring, it should be fixed by #1619 here: https://github.com/Netflix/dispatch/pull/1619/files#diff-a18f25a281e12ef3416fa7f3165ea811fdfd1dbafd12cddaf19f62d1e1835b07R41

We're hoping to merge and released this change within the next few weeks.

**Comment by vikassinha2019** [comment]
Thanks Kevin!
I see that PR got merged in master, but looks like it is not fully functional. 
e.g. with the pull from master branch, Plugins are not showing any more under settings. 

following error shows up in logs:
`  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "dispatch_organization_default.incident_role" does not exist
LINE 2: FROM dispatch_organization_default.incident_role 
`

Can you please confirm the last working version/tag that should be used.

TIA

**Comment by kevgliss** [comment]
Did you run `dispatch database upgrade` when pulling from master?

**Comment by vikassinha2019** [comment]
> Did you run `dispatch database upgrade` when pulling from master?

I was running a fresh installation with the latest pull from master.

**Comment by vikassinha2019** [comment]
Running a fresh installation gives following error at the end. 

```
Example data loaded. Navigate to /register and create a new user.
Running standard database migrations...
Starting dispatch_postgres_1 ... done
Creating dispatch_core_1     ... done
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 790, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 387, in upgrade_database
    alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/dispatch/database/revisions/tenant/env.py", line 83, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.9/site-packages/dispatch/database/revisions/tenant/env.py", line 73, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 612, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.9/site-packages/dispatch/database/revisions/tenant/versions/2021-09-16_3820a792d88a.py", line 138, in upgrade
    jira_config = JiraConfiguration(
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for JiraConfiguration
api_url
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
browser_url
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
default_project_id
  none is not an allowed value (type=type_error.none.not_allowed)
default_issue_type_name
  none is not an allowed value (type=type_error.none.not_allowed)
Cleaning up...
dispatch@dispatch-alp-we-vm:~/opsgenie_test/dispatch-docker$ 
```
Earlier it was listing up error for pagerduty, which went away once we added dummy values in there. When we added dummy value for Jira, then installation process completed successfully. I believe with empty values of those fields, the installation should work, like it used to earlier. 

Later when we try to create incident in Dispatch, its opsgenie plugin failed with the following error:

```
  File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_opsgenie/plugin.py", line 41, in get
    return get_oncall(self.configuration.api_key, service_id)
AttributeError: 'NoneType' object has no attribute 'api_key'
```

We did specify OPSGENIE_API_KEY and OPSGENIE_TEAM_ID values in .env file, but somehow it is not picking those values.

**Comment by kevgliss** [comment]
Hopefully #1689 fixes your migration issue.

**Comment by mvilanova** [comment]
@vikassinha2019 can you describe the other issues you found in master? We're planning to cut a new release this week and would like to include all bug fixes we can.

**Comment by vikassinha2019** [comment]
@mvilanova following are 2 issues I found so far.

1. Ticket creation failure due to opsgenie page_oncall call failure
`  File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_opsgenie/plugin.py", line 51, in page
    return page_oncall(
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_opsgenie/service.py", line 33, in page_oncall
    "alias": incident_title + incident_name,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

2. In Dispatch UI, for Slack config, socket mode field is mandatory field, even if we want to use API mode. I also do not see option in there to specify slack workspace name in the form, which we used to specify earlier in config file. 

Will update here if found any other issue as well.

**Comment by vikassinha2019** [comment]
For opsgenie, I have applied a fix. please let me know if I can get permissions to raise a PR for that. Or you can simply review it here. 

dispatch_opsgenie/plugin.py
`        return page_oncall(
            self.configuration.api_key, service_id, incident_name, incident_title, incident_description
        )
`

dispatch_opsgenie/service.py
`
def page_oncall(
    api_key: str, service_id: str, incident_title: str, incident_name: str, incident_description: str
) -> str:
    data = {
        "message": incident_name,
        "alias": incident_name,
        "description": incident_description,
        "responders":[ {"id": service_id, "type":"schedule"}],
    }

`

**Comment by vikassinha2019** [comment]
Suggestion for slack issue worked. If the images can be updated accordingly in the slack config [document](https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack) ; it will people like me who skim through documentation :)
Thanks for the prompt response.
