### ISSUE TITLE
Slack channel creation fails

### ISSUE THREAD

**Issue by jtorvald** [Netflix/dispatch#1729]
**Describe the bug**
When creating a new incident I get the following error in the logs:

The channel creation fails and that response does not seems to be checked because the following actions also fail because of a missing channel_id
```

web_1        | INFO:     172.20.0.1:40684 - "POST /api/v1/default/incidents HTTP/1.1" 200 OK
web_1        | INFO:Dispatch Core App: Creation of incident conversation failed. Reason: 'NoneType' object has no attribute 'lower':/usr/local/lib/python3.9/site-packages/dispatch/event/service.py:log:100
web_1        | ERROR:'NoneType' object has no attribute 'lower':/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py:incident_create_flow:716
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 688, in incident_create_flow
web_1        |     conversation = create_conversation(incident, db_session)
web_1        |   File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 379, in create_conversation
web_1        |     conversation = plugin.instance.create(incident.name)
web_1        |   File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 122, in wrapper
web_1        |     return func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 106, in wrapper
web_1        |     result = func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/plugin.py", line 69, in create
web_1        |     return create_conversation(client, name, self.configuration.private_channels)
web_1        |   File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/service.py", line 270, in create_conversation
web_1        |     name=name.lower(),  # slack disallows upperCase
web_1        | AttributeError: 'NoneType' object has no attribute 'lower'
web_1        | WARNING:External ticket not updated. No ticket plugin enabled.:/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py:update_external_incident_ticket:177
web_1        | INFO:Dispatch Core App: Adding participant(s) to incident conversation failed. Reason: 'NoneType' object has no attribute 'channel_id':/usr/local/lib/python3.9/site-packages/dispatch/event/service.py:log:100
web_1        | ERROR:'NoneType' object has no attribute 'channel_id':/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py:add_participants_to_conversation:438
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 430, in add_participants_to_conversation
web_1        |     plugin.instance.add(incident.conversation.channel_id, participant_emails)
web_1        | AttributeError: 'NoneType' object has no attribute 'channel_id'
```

**Additional context**
```
$ git log --pretty=format:'%h' -n 1
4f35c254
```

**Comment by Fgerthoffert** [comment]
After removing the url check at https://github.com/Netflix/dispatch/blob/e30705938e970d8ef0dfdd04246a3f3004a6a44f/src/dispatch/models.py#L139 I managed to get through and see the channels created.

What seems to be happening here is that if for some reason the user's weblink cannot be accessed (and if I understand properly it does not seem to be a default Slack field), this field gets assigned the value `Unknown` in [SlackContactPlugin.get()](https://github.com/Netflix/dispatch/blob/e30705938e970d8ef0dfdd04246a3f3004a6a44f/src/dispatch/plugins/dispatch_slack/plugin.py#L184), which is not a url and therefore fails the [url validation check](https://github.com/Netflix/dispatch/blob/e30705938e970d8ef0dfdd04246a3f3004a6a44f/src/dispatch/models.py#L139).

**Comment by mvilanova** [comment]
@Fgerthoffert @jtorvald https://github.com/Netflix/dispatch/pull/1741 should fix your issues when a contact plugin is not enabled or enabled, but the weblink is not available. Let me know.
