### ISSUE TITLE
Bug: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'

### ISSUE THREAD

**Issue by jtorvald** [Netflix/dispatch#1734]
**Describe the bug**
In the error log I get an error about datetime.datetime missing on a nodetype. Not sure what is the cause of this. Maybe bad install or a bug in the code. I thought that it might be good to report anyway.

```
DEBUG:Running job Job(interval=5, unit=minutes, do=calculate_incidents_response_cost, args=(), kwargs={}):/usr/local/lib/python3.9/site-packages/schedule/__init__.py:run:660
ERROR:unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime':/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/scheduled.py:calculate_incidents_response_cost:77
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/scheduled.py", line 59, in calculate_incidents_response_cost
    amount = calculate_incident_response_cost(incident.id, db_session)
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/service.py", line 135, in calculate_incident_response_cost
    participant_role_time = participant_role_renounced_at - participant_role_assumed_at
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
ERROR:unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime':/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/scheduled.py:calculate_incidents_response_cost:77
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/scheduled.py", line 59, in calculate_incidents_response_cost
    amount = calculate_incident_response_cost(incident.id, db_session)
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/service.py", line 135, in calculate_incident_response_cost
    participant_role_time = participant_role_renounced_at - participant_role_assumed_at
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
ERROR:unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime':/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/scheduled.py:calculate_incidents_response_cost:77
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/scheduled.py", line 59, in calculate_incidents_response_cost
    amount = calculate_incident_response_cost(incident.id, db_session)
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/service.py", line 135, in calculate_incident_response_cost
    participant_role_time = participant_role_renounced_at - participant_role_assumed_at
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
ERROR:unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime':/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/scheduled.py:calculate_incidents_response_cost:77
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/scheduled.py", line 59, in calculate_incidents_response_cost
    amount = calculate_incident_response_cost(incident.id, db_session)
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident_cost/service.py", line 135, in calculate_incident_response_cost
    participant_role_time = participant_role_renounced_at - participant_role_assumed_at
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'

```

**Additional context**
```
$ git log --pretty=format:'%h' -n 1
4f35c254
```

**Comment by mvilanova** [comment]
Marking them as closed would mark them as stable first. We may have a bug there... We'll take a look at it.
