### ISSUE TITLE
value is not a valid email address (type=value_error.email)

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#1832]
With v20211116, on a fresh installation of Dispatch with basic auth, we are getting following error

value is not a valid email address (type=value_error.email)

<img width="1274" alt="Screenshot 2021-11-20 at 12 06 16 AM" src="https://user-images.githubusercontent.com/52274121/142674689-6bcbe825-f930-44de-88b3-df829dafe174.png">

The stack trace is as follows:
response -> items -> 0 -> project -> owner_email
  value is not a valid email address (type=value_error.email)
response -> items -> 1 -> project -> owner_email
  value is not a valid email address (type=value_error.email)
response -> items -> 2 -> project -> owner_email
  value is not a valid email address (type=value_error.email)
INFO:     122.172.60.107:55715 - "GET /api/v1/default/incident_types?itemsPerPage=-1 HTTP/1.1" 422 Unprocessable Entity
INFO:     122.172.60.107:55718 - "GET /api/v1/default/incidents/metric/forecast HTTP/1.1" 200 OK
INFO:     122.172.60.107:55714 - "GET /api/v1/default/incidents/metric/forecast?itemsPerPage=-1&descending[]=false&sortBy[]=reported_at&include[]=closed_at&include[]=created_at&include[]=total_cost&include[]=stable_at&include[]=reported_at&include[]=incident_priority&include[]=incident_type&include[]=status&include[]=primary_team&include[]=primary_location&include[]=tags&include[]=duplicates&include[]=project&include[]=name&include[]=title&filter=%7B%22and%22:[%7B%22or%22:[%7B%22and%22:[%7B%22model%22:%22Incident%22,%22field%22:%22reported_at%22,%22op%22:%22%3E%3D%22,%22value%22:%222021-05-19%22%7D,%7B%22model%22:%22Incident%22,%22field%22:%22reported_at%22,%22op%22:%22%3C%3D%22,%22value%22:%222021-11-19%22%7D]%7D]%7D]%7D HTTP/1.1" 200 OK
ERROR:dispatch.main:10 validation errors for IncidentPagination
items -> 0 -> incident_priority -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 0 -> incident_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 0 -> tags -> 0 -> tag_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 0 -> tags -> 0 -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 1 -> incident_priority -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 1 -> incident_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 2 -> incident_priority -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 2 -> incident_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 3 -> incident_priority -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 3 -> incident_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 184, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 172, in dispatch
    raise e from None
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 168, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_asgi/middleware.py", line 22, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/sentry_asgi/middleware.py", line 19, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 144, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident/views.py", line 81, in get_incidents
    return json.loads(IncidentPagination(**pagination).json(include=include_fields))
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 10 validation errors for IncidentPagination
items -> 0 -> incident_priority -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 0 -> incident_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 0 -> tags -> 0 -> tag_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 0 -> tags -> 0 -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 1 -> incident_priority -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 1 -> incident_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 2 -> incident_priority -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 2 -> incident_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 3 -> incident_priority -> project -> owner_email
  value is not a valid email address (type=value_error.email)
items -> 3 -> incident_type -> project -> owner_email
  value is not a valid email address (type=value_error.email)
INFO:     122.172.60.107:55716 - "GET /api/v1/default/incidents?itemsPerPage=-1&descending[]=false&sortBy[]=reported_at&include[]=closed_at&include[]=created_at&include[]=total_cost&include[]=stable_at&include[]=reported_at&include[]=incident_priority&include[]=incident_type&include[]=status&include[]=primary_team&include[]=primary_location&include[]=tags&include[]=duplicates&include[]=project&include[]=name&include[]=title&filter=%7B%22and%22:[%7B%22or%22:[%7B%22and%22:[%7B%22model%22:%22Incident%22,%22field%22:%22reported_at%22,%22op%22:%22%3E%3D%22,%22value%22:%222021-05-19%22%7D,%7B%22model%22:%22Incident%22,%22field%22:%22reported_at%22,%22op%22:%22%3C%3D%22,%22value%22:%222021-11-19%22%7D]%7D]%7D]%7D HTTP/1.1" 422 Unprocessable Entity

**Comment by kevgliss** [comment]
Can you see pull master and see if #1836 fixes your issue?

**Comment by vikassinha2019** [comment]
Nope, still facing same issue with the master pull that has #1836 included in it.

**Comment by vikassinha2019** [comment]
Tried again with the latest pull. It is working fine.

**Comment by vikassinha2019** [comment]
Please ignore my last comment. The fresh installation was working with basic Auth. the fix in #1836 also is not solving the issue. I am using Azure AD authentication.

**Comment by vikassinha2019** [comment]
issue still persists

**Comment by mvilanova** [comment]
@vikassinha2019 are you still experiencing this issue? If not, please feel free to close it.

**Comment by pdehlke** [comment]
I am having the same issue as of today, using v20220119 in https://github.com/Netflix/dispatch-docker/

**Comment by mvilanova** [comment]
Ok, thanks for letting me know. I’ll look into it.

**Comment by mvilanova** [comment]
Is that using the sample data or not?

**Comment by pdehlke** [comment]
Yes, using the sample data, because electing not to use the sample data fails even more spectacularly:

Do you want to load example data (WARNING: this will remove all existing database data) (y/N)?n
Running standard database migrations...
Creating dispatch_core_1 ... done
Creating dispatch_web_run ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "dispatch_user_organization" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 790, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 387, in upgrade_database
    alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/dispatch/database/revisions/core/env.py", line 70, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.9/site-packages/dispatch/database/revisions/core/env.py", line 64, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 620, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.9/site-packages/dispatch/database/revisions/core/versions/2021-06-15_0ab4f8f54bfa.py", line 21, in upgrade
    op.alter_column(
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/ops.py", line 1880, in alter_column
    return operations.invoke(alt)
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/base.py", line 392, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 50, in alter_column
    operations.impl.alter_column(
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/postgresql.py", line 173, in alter_column
    super(PostgresqlImpl, self).alter_column(
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/impl.py", line 231, in alter_column
    self._exec(
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/impl.py", line 197, in _exec
    return conn.execute(construct, multiparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "dispatch_user_organization" does not exist

[SQL: ALTER TABLE dispatch_user_organization ALTER COLUMN dispatch_user_id SET NOT NULL]
(Background on this error at: http://sqlalche.me/e/13/f405)
ERROR: 1
Cleaning up...

**Comment by mvilanova** [comment]
Ugh, that's no bueno. The script might be missing a dispatch database init after running the database migrations. I'll put out a fix for it soon.

**Comment by pdehlke** [comment]
More information on this.

If I use v20211015 or earlier in dispatch-docker, everything works fine with the sample data. If I use v20211116 or later, I get this issue.

**Comment by mvilanova** [comment]
The sample data has fallen behind all the changes to master and needs to be rebuilt.

**Comment by pdehlke** [comment]
So is this going to be a "won't fix"?

**Comment by kevgliss** [comment]
We are planning to have a release in the next few days. I will update the example data accordingly.
