### ISSUE TITLE
mjml module not working for sending email notifications

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#1844]
**Describe the bug**
We have enabled email plugin to send out notification mails on ticket update. The status change of the dispatch ticket is triggerent slack messages fine. However, it is failing on sending email notifications.

ERROR:dispatch.messaging.email.utils:internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../lib/index'
Require stack:
- /usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/.bin/mjml
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/.bin/mjml:3:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/.bin/mjml'
  ]
}

ERROR:dispatch.decorators:MJML template processing failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 85, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 1132, in incident_update_flow
    send_incident_update_notifications(incident, previous_incident, db_session)
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident/messaging.py", line 395, in send_incident_update_notifications
    notification_service.filter_and_send(
  File "/usr/local/lib/python3.9/site-packages/dispatch/notification/service.py", line 135, in filter_and_send
    send(
  File "/usr/local/lib/python3.9/site-packages/dispatch/notification/service.py", line 109, in send
    plugin.instance.send(
  File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_sendgrid/plugin.py", line 89, in send
    message_body = create_message_body(notification_template, notification_type, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/messaging/email/utils.py", line 90, in create_message_body
    return render_html(template.render(**kwargs))
  File "/usr/local/lib/python3.9/site-packages/dispatch/messaging/email/utils.py", line 106, in render_html
    raise Exception("MJML template processing failed.")
Exception: MJML template processing failed.

**To Reproduce**
Using v20211015 release.
The content of the file /usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/.bin/mjml is following

-------
#!/usr/bin/env node

require('../lib/index')
require('mjml-cli')
-------

However, the path '../lib/index' does not exist.

root@web-78c8cc85f8-l266l:/usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/.bin# cat mjml
#!/usr/bin/env node

require('../lib/index')
require('mjml-cli')
root@web-78c8cc85f8-l266l:/usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/.bin# ls -al ../lib/index
ls: cannot access '../lib/index': No such file or directory
root@web-78c8cc85f8-l266l:/usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/.bin# 

Most probably it is a NPM issue, but was this email notification working earlier? Or is there any fix we can apply in Dispatch to pass this error.

**Comment by kevgliss** [comment]
Hmm, we are currently using that release and email notifications are working correctly. Judging by this old issue, maybe a re-install fixes it? https://github.com/mjmlio/mjml/issues/507

**Comment by vikassinha2019** [comment]
Yes, reinstalling npm plugin is solving the issue. Followed below steps:

1. rm /usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/.bin/mjml
2. npm uninstall mjml
3. npm i mjml

But strangely even with newly built image, this issue persists. Hence, i need to do above steps to make the notifications working.

Let me check mjml forums.

**Comment by vikassinha2019** [comment]
@kevgliss for me a different mjml config path is working. 
I have changed following:
default=f"{os.path.dirname(os.path.realpath(__file__))}/static/dispatch/node_modules/.bin",
to
default=f"{os.path.dirname(os.path.realpath(__file__))}/static/dispatch/node_modules/mjml/bin",
 
in dispatch/src/dispatch/config.py

**Comment by kevgliss** [comment]
You can also set the `MJML_PATH` 

See: https://hawkins.gitbook.io/dispatch/administration-guide/server#mjml_path-default-node_modules-.bin

**Comment by vikassinha2019** [comment]
ok, so in my case, can i set MJML_PATH to '/node_modules/mjml/bin' in .env file or do I need to specify full path '/usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/mjml/bin' ?

**Comment by vikassinha2019** [comment]
tried with both 'MJML_PATH=/node_modules/mjml/bin' and 'MJML_PATH=/usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/mjml/bin' in .env, but the changes are not reflecting there.

**Comment by vikassinha2019** [comment]
> tried with both 'MJML_PATH=/node_modules/mjml/bin' and 'MJML_PATH=/usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/node_modules/mjml/bin' in .env, but the changes are not reflecting there.

any comments on this?

**Comment by mvilanova** [comment]
@vikassinha2019 are you still experiencing issues with this? If so, please feel free to close.
