### ISSUE TITLE
Unable to import fbprophet, some metrics will not be usable.

### ISSUE THREAD

**Issue by B3lak0r** [Netflix/dispatch#196]
1.- Required plugins added.
2.- Dispatch built with success.
3.-  UI accesible.
4.- Documents, Service, Incident types available to be created by the UI. 

But no able to save incidents, getting some 500 and 422 error codes.

Tracking the container logs for those errors I've got:

```
docker logs 60a0c55565ac -f --until=2s
No metric providers specified metrics will not be sent.
WARNING:  Unable to import fbprophet, some metrics will not be usable.
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

```

Recreating the error / bug when saving the incident using the UI:

```
INFO:     192.168.169.11:49991 - "GET /api/v1/incidents/metric/forecast/all HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 149, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 165, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 121, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/views.py", line 144, in get_incident_forecast
    return make_forecast(db_session=db_session, incident_type=incident_type)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/metrics.py", line 72, in make_forecast
    dataframe = pd.DataFrame.from_dict(dataframe_dict)
NameError: name 'pd' is not defined
```

and as explained here:

https://github.com/Netflix/dispatch-docker/issues/34#issuecomment-607221358

 In the file https://github.com/Netflix/dispatch/blob/develop/src/dispatch/incident/metrics.py

States (from line 18 to 22)

```
try:
    from fbprophet import Prophet
    import pandas as pd
except ImportError:
    log.warning("Unable to import fbprophet, some metrics will not be usable.")

```
It seems that module fbprophet is missing and/or was not imported during the installation.

**Comment by kevgliss** [comment]
Yes, fbprohet is actually quite a pain to install/deploy (we were/are having trouble getting it deployed internally). Initially, we thought we could make it optional and just not have those metrics. But because the math is relatively straightforward and we had a data scientist on our team willing to do the work we're planning on replacing it with a pure python version (instead of all the C that fbprophet requires). 

I don't have a firm timeline on when we might be finished with that, but it is a work in progress.

**Comment by sarahcthekey** [comment]
OK thanks @kevgliss 

Can I ask if you have more detailed documentation on how the incident conversation data flow happens? I.e. once an incident is opened, what happens in slack? I have configured an app in our Slack workspace and configured slash commands which work, but each time I test it mentions that I need to do them in an incident conversation. 

I'm still having an issue with errors (same as above) but incidents are being created anyway and showing in the front end.

I'm confused on the link between Slack conversations and Dispatch app. Thanks

**Comment by kevgliss** [comment]
Hi @sarahcthekey we should probably build out our [user guides](https://hawkins.gitbook.io/dispatch/user-guide) a bit more. Essentially, when you create an incident you could see a new incident channel created that the reporter and commander are invited to. You should also see a notification message in the [notification channels](https://hawkins.gitbook.io/dispatch/configuration/app#incident_notification_conversations-default) if they have been defined.

Once your incident channel has been created, you can then run commands. We use _where_ the command was sent from to map the actions taken to the correct incident (as you can have many at once).

**Comment by sarahcthekey** [comment]
Thanks for the info @kevgliss. We've decided to put this POD project on hold now, ideally we'd like to spend time removing Pager Duty as a hard coded dependency and I think this is still a little too new to implement in our own environment. It's great what you've done so far though, keep it up and I'll definitely check back in a few months once the project has matured some more.

**Comment by B3lak0r** [comment]
Hi, been out for a while and I see it's been some changes, but now even having the incident priority in the UI, it seems @kevgliss  something is still missing:

`sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column incident_priority.page_commander does not exist
LINE 2: ...incident_priority.name AS incident_priority_name, incident_p...`
