### ISSUE TITLE
Config 'DISPATCH_ENCRYPTION_KEY' is missing on Docker Run

### ISSUE THREAD

**Issue by Keetmalin** [Netflix/dispatch#2122]
**Describe the bug**
When I try to run the [docker image](ghcr.io/netflix/dispatch/dispatch-image:v20220322) provided in this repo, I get the following error. 

```
KeyError: "Config 'DISPATCH_ENCRYPTION_KEY' is missing, and has no default."
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 5, in <module>
    from dispatch.cli import entrypoint
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 6, in <module>
    from dispatch import __version__, config
  File "/usr/local/lib/python3.9/site-packages/dispatch/config.py", line 96, in <module>
    DISPATCH_ENCRYPTION_KEY = config("DISPATCH_ENCRYPTION_KEY", cast=Secret)
  File "/usr/local/lib/python3.9/site-packages/starlette/config.py", line 84, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.9/site-packages/starlette/config.py", line 97, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'DISPATCH_ENCRYPTION_KEY' is missing, and has no default."
```
The command I used was:
`sudo docker run ghcr.io/netflix/dispatch/dispatch-image:v20220322`

I have a `.env` file and I tried to pass it to the following command, with:
`sudo docker run ghcr.io/netflix/dispatch/dispatch-image:v20220322 --env DISPATCH_ENCRYPTION_KEY=somekey`
or
`sudo docker run ghcr.io/netflix/dispatch/dispatch-image:v20220322 --env-file .env`

I am assuming there is a different way to pass the .env into the docker image. I tried building the docker image manually, but I still get the same error.

**To Reproduce**

- run docker image with following command
`sudo docker run ghcr.io/netflix/dispatch/dispatch-image:v20220322`

**Expected behavior**

- Dispatch to run as expected.

**Screenshots**
<img width="943" alt="image" src="https://user-images.githubusercontent.com/12439263/160529509-c3bee83e-5c13-4439-8a04-8ad4e67633ec.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version [e.g. 12.2.1]

**Additional context**

Docker version: Docker version 20.10.14, build a224086

**Comment by Keetmalin** [comment]
Sorted this out. It was a mistake on the way I ran the docker command. Command should be:

`sudo docker run  --env-file .env ghcr.io/netflix/dispatch/dispatch-image:v20220322`
