### ISSUE TITLE
Possible typo in cli.py (clean_incident_artifacts function)

### ISSUE THREAD

**Issue by AlexaKelley** [Netflix/dispatch#213]
Hello, I am working on setting up a dispatch instance and I have come across the following error.

`Starting dispatch_postgres_1 ... done
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 845, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 408, in clean_incident_artifacts
    from dispatch.plugins.dispatch_google.drive.config import GOOGLE_DOMAIN
ModuleNotFoundError: No module named 'dispatch.plugins.dispatch_google.drive.config'`

this was from running `docker-compose run web incident clean`

I don't have a full development instance set up to test this. Can you confirm if this function is working properly for you in your deployment? I suspect there may be a misnamed module.

`def clean_incident_artifacts(pattern):
    """This command will clean up incident artifacts. Useful for development."""
    import re
    from dispatch.plugins.dispatch_google.drive.config import GOOGLE_DOMAIN`

Thank you
-Alexa Kelley

**Comment by mvilanova** [comment]
Yep, that's a bug. The import should be `from dispatch.plugins.dispatch_google.config import GOOGLE_DOMAIN`. We will get it fixed. Thanks for letting us know!

**Comment by mvilanova** [comment]
Fixed in #214. Thanks again.
