### ISSUE TITLE
Unable to install dispatch locally

### ISSUE THREAD

**Issue by Georgios90** [Netflix/dispatch#2630]
**Describe the bug**
When trying to install dispatch i get the following error

Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 794, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 23, in dispatch_cli
    configure_logging()
  File "/usr/local/lib/python3.9/site-packages/dispatch/logging.py", line 6, in configure_logging
    level = LOG_LEVEL.upper()
AttributeError: 'int' object has no attribute 'upper'
Cleaning up...

This is done locally on a mac

**Comment by mvilanova** [comment]
Did you pull the latest version of the code. This should have been fixed in https://github.com/Netflix/dispatch/pull/2544/

**Comment by Georgios90** [comment]
I just did yes

**Comment by Georgios90** [comment]
well sorry I was using git clone https://github.com/Netflix/dispatch-docker.git

**Comment by Georgios90** [comment]
which is mentioned here https://hawkins.gitbook.io/dispatch/installation

**Comment by mvilanova** [comment]
Change `latest` in https://github.com/Netflix/dispatch-docker/blob/master/docker-compose.yml#L22 with `master`. The changes mentioned above haven't been released yet.
