### ISSUE TITLE
Jira Plugin Unable to Create tickets

### ISSUE THREAD

**Issue by that-devops-guy** [Netflix/dispatch#2715]
**Describe the bug**
Jira plugin is unable to create tickets in new release

**To Reproduce**
1. Pull the latest release
2. Install and Configure Jira plugin
3. Enable Jira plugin and  Jira Plugin as Default Ticketing tool
4. See Error

**Expected behavior**
Dispatch should be able to create JIRA  tickets through REST API

**Error**
```bash
    INFO:     127.0.0.1:59230 - "POST /default/incidents HTTP/1.1" 200 OK
    ERROR:dispatch.decorators:list index out of range
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 85, in wrapper
        result = func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 646, in incident_create_flow
        ticket = create_incident_ticket(incident, db_session)
      File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 136, in create_incident_ticket
        ticket = plugin.instance.create(
      File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 122, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 106, in wrapper
        result = func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_jira/plugin.py", line 261, in create
        assignee = get_user_field(
      File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_jira/plugin.py", line 82, in get_user_field
        user = next(
      File "/usr/local/lib/python3.9/site-packages/jira/client.py", line 170, in __next__
        return self.iterable[self.current - 1]
    IndexError: list index out of range
```
**Jira Configuration**
![Screenshot from 2022-11-21 23-00-39](https://user-images.githubusercontent.com/30006449/203123174-081e0f7e-0641-40a1-978c-79423ac37ea8.jpg)

**Comment by kevgliss** [comment]
Are you using the latest tagged release or the master branch?

**Comment by that-devops-guy** [comment]
I'm using the master branch

**Comment by kevgliss** [comment]
Does the current assignee have a user account in your jira instance? I believe the plugin is complaining about being unable to find the user within Jira.

**Comment by that-devops-guy** [comment]
Current assignee as in The dispatch user creating the ticket ? Yes it has a user account in Jira.
Even if it's unable/failed to create with current assignee is it possible to follow the same scenario in hosting type server. where it fallbacks to default jira user for creating tickets.

**Comment by mvilanova** [comment]
@that-devops-guy is the hosting type correct in your Jira plugin configuration? There are two options: `server` and `cloud`. It needs to be set to the correct one for Dispatch to be able to search and return the Jira user. Like @kevgliss suggested, make sure the email address used to set the commander role has an account in your Jira instance.
