### ISSUE TITLE
Basic Authentication setup

### ISSUE THREAD

**Issue by tomarv2** [Netflix/dispatch#303]
@kevgliss 

I need to set up some sort of authentication. Looking for some ideas?

I know you talked about basic auth. How do I set it up?

**Comment by kevgliss** [comment]
The default auth flow is basic auth, once you get the app running you should be presented with a /login form. It has a link to /register once you register you will be authenticated (today we don't limit registration or confirm it).

**Comment by alexandrosgkesos** [comment]
Hello all,
I have as well some trouble configuring the authentication.
When i install with the default .env.example 
( empty: DISPATCH_AUTHENTICATION_PROVIDER_SLUG= )
then i can't create some "items", like the Incident Types, getting " IncidentType not created. Reason: undefined "

Also, if that's the "Basic auth"..when i enter the Dispatch server IP, i go directly to the Incident Report page, not to a /login form.
If i go manually to http://127.0.0.1/login or register, i get HTTP404

**Comment by tomarv2** [comment]
I am also getting 404 what am I missing?

**Comment by kevgliss** [comment]
If you're setting `DISPATCH_AUTHENTICATION_PROVIDER_SLUG=` you're actually _disabling_ authentication entirely.

If you want to use basic auth you can either do so explicitly via:

`DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic` 

or you can simply not set it at all (as `dispatch-auth-provider-basic`) is the default. 

The default .env.example is typically used within a docker container (that managed their own auth). But we could unset it there as well if it's confusing to folks.

The reason for the 404 is because for non-basic auth flows we don't advertise the /login or /register routes (as they aren't used).

@alexandrosgkesos would you mind open up a separate issue for IncidentType creation? We don't do a good job at returning the actual error in the UI but it should be there if you inspect the response.

**Comment by tomarv2** [comment]
@kevgliss :

```
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic
DISPATCH_AUTHENTICATION_DEFAULT_USER=tomarv2@xxxxx.com
```

getting below error:

```
web_1       | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
web_1       | INFO:     172.24.0.1:51792 - "GET /services HTTP/1.1" 200 OK
web_1       | ERROR:    Unable to find slug: dispatch-auth-provider-basic in self.all version 1: <generator object PluginManager.all at 0x7f78303312e0> or version 2: <generator object PluginManager.all at 0x7f78303312e0>
web_1       | ERROR:    Unable to find slug: dispatch-auth-provider-basic in self.all version 1: <generator object PluginManager.all at 0x7f7830331350> or version 2: <generator object PluginManager.all at 0x7f7830331350>
web_1       | INFO:     172.24.0.1:51792 - "GET /api/v1/terms/ HTTP/1.1" 500 Internal Server Error
web_1       | ERROR:    Exception in ASGI application
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
web_1       |     result = await app(self.scope, self.receive, self.send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
web_1       |     return await self.app(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
web_1       |     await self.middleware_stack(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1       |     raise exc from None
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1       |     await self.app(scope, receive, _send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1       |     await response(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
web_1       |     async for chunk in self.body_iterator:
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1       |     task.result()
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1       |     await self.app(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
web_1       |     raise exc from None
web_1       |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
web_1       |     await self.app(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1       |     await response(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
web_1       |     async for chunk in self.body_iterator:
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1       |     task.result()
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1       |     await self.app(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1       |     await response(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
web_1       |     async for chunk in self.body_iterator:
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1       |     task.result()
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1       |     await self.app(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1       |     raise exc from None
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1       |     await self.app(scope, receive, sender)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
web_1       |     await route.handle(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
web_1       |     await self.app(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 149, in __call__
web_1       |     await super().__call__(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
web_1       |     await self.middleware_stack(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1       |     raise exc from None
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1       |     await self.app(scope, receive, _send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1       |     raise exc from None
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1       |     await self.app(scope, receive, sender)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
web_1       |     await route.handle(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
web_1       |     await self.app(scope, receive, send)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
web_1       |     response = await func(request)
web_1       |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 186, in app
web_1       |     solved_result = await solve_dependencies(
web_1       |   File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 510, in solve_dependencies
web_1       |     solved = await run_in_threadpool(call, **sub_values)
web_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
web_1       |     return await loop.run_in_executor(None, func, *args)
web_1       |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
web_1       |     result = self.fn(*self.args, **self.kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/dispatch/auth/service.py", line 22, in get_current_user
web_1       |     auth_plugin = plugins.get(DISPATCH_AUTHENTICATION_PROVIDER_SLUG)
web_1       |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/base/manager.py", line 43, in get
web_1       |     raise KeyError(slug)
web_1       | KeyError: 'dispatch-auth-provider-basic'
web_1       | INFO:     172.24.0.1:51790 - "GET /api/v1/incident_priorities/ HTTP/1.1" 500 Internal Server Error
web_1       | ERROR:    Exception in ASGI application
web_1       | Traceback (most recent call last):
```

**Comment by kevgliss** [comment]
Do you have the latest code?

**Comment by tomarv2** [comment]
i am using the one from the master branch, which I think was 17days ago..

**Comment by kevgliss** [comment]
Ah, basic authentication has not yet made it into master. We are planning to release it to master next week.

**Comment by kevgliss** [comment]
Basic auth is now in master.
