### ISSUE TITLE
Dispatch upgrade process

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#3034]
Hi,

We are using an 2021 Nov release of Dispatch in our environment. And we are planning to upgrade it to latest build. 

However, [documentation](https://hawkins.gitbook.io/dispatch/upgrading#running-migrations) around this process needs more details. 

We are running Dispatch on K8s with Azure SaaS potgres db. So, how should we perform the update? This is my understanding so far:
1. Build the application with new product files and old database. 
2. Run pods with the new build
3. Run 'dispatch database upgrade' command via Dispatch cli from one of the pod
4. Access the application

Can you please verify if this is the process we should follow for the Dispatch upgrade?

**Comment by vikassinha2019** [comment]
@kevgliss a quick help around this please.

**Comment by vikassinha2019** [comment]
I followed the above mentioned upgrade steps, but I am getting a blank page with following fail call after SSO login:

`"GET /default/auth/me HTTP/1.1" 422 Unprocessable Entity`

The logs are showing following error:

```
ERROR:dispatch.main:1 validation error for UserRead
response -> projects -> 0 -> project -> owner_email
  value is not a valid email address (type=value_error.email)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 185, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 176, in dispatch
    raise e from None
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 168, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 80, in call_next
```

dispatch database history output for reference:

```
/# dispatch database history
No JWT Email Override specified. 'email' is expected in the idtoken.
c0bc938b058e, 8f364cf49a23 -> e0d568f345c9 (head) (mergepoint), Merge revision
0ab4f8f54bfa -> c0bc938b058e, Makes an organization's slug into a column.
0ab4f8f54bfa -> 8f364cf49a23, Recreates dispatch_user_organization_dispatch_user_id_fkey and dispatch_user_organization_organization_id_fkey
f011c050b9ba -> 0ab4f8f54bfa (branchpoint), empty message
<base> -> f011c050b9ba, Initial core revision
```

Please help in getting the upgrade through.

**Comment by vikassinha2019** [comment]
Okay, so in the old version we did not have owner assigned to Project under Organisation. Once I updated the owner_email value in project table with new version, page started loading.
Currently, I am getting a custom plugin error. Let me keep this issue opened until upgrade is completed.

**Comment by vikassinha2019** [comment]
Upgrade completed fine. So, the process is simply to build Dispatch with new application code and DB migration step was taken care in that only.
