### ISSUE TITLE
Issue with INCIDENT_PLUGIN_TASK_SLUG

### ISSUE THREAD

**Issue by jffz** [Netflix/dispatch#338]
I followed the doc and created the oauth and api tokens for Gsuite but having an error on incident creation, I might be missing something.

``` 
Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 35, in wrapper
     result = func(*args, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/dispatch/task/scheduled.py", line 98, in sync_active_stable_tasks
     sync_tasks(db_session, incidents, notify=True)
   File "/usr/local/lib/python3.8/site-packages/dispatch/task/scheduled.py", line 49, in sync_tasks
     drive_task_plugin = plugins.get(INCIDENT_PLUGIN_TASK_SLUG)
   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/base/manager.py", line 43, in get
     raise KeyError(slug)
 KeyError: '"google-drive-task"'
 Unable to find slug: "google-drive-task" in self.all version 1: <generator object PluginManager.all at 0x7fac1ba60900> or version 2: <generator object PluginManager.all at 0x7fac1ba60900>
```

**Comment by mvilanova** [comment]
@jffz did you set INCIDENT_PLUGIN_TASK_SLUG to `"google-drive-task"` in your `.env` file by any chance?

**Comment by jffz** [comment]
Yes that is what it is set to (let it to default)

**Comment by mvilanova** [comment]
@jffz you don't need to set it, as it's the default value (see [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/config.py#L158)), but if you choose to do so, set it without quotes: `INCIDENT_PLUGIN_TASK_SLUG=google-drive-task`.

**Comment by mvilanova** [comment]
@jffz are you still having this issue, or were you able to fix it after my suggestion above?
