### ISSUE TITLE
Issues with Basic Auth

### ISSUE THREAD

**Issue by bsundsrud** [Netflix/dispatch#360]
I'm trying to get basic auth set up and I have a few issues.  I'm not using the dispatch-docker project as I'm trying to deploy to kubernetes.

1) I've set `DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic`, I was running into issues with the Vue app not redirecting to /login until I realized I had to set `VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG` at container build time, as well.  Even with this, `/incidents/report` fails to get Type and Priority because the JWT token is not sent to the API, even though it is present in local storage.  It seems the Authorization header isn't being set correctly or in all places?

When visiting `/incidents/report` with a valid token in local storage:
```
INFO:     172.16.7.67:58766 - "GET /api/v1/incident_priorities/?sortBy[]=view_order&descending[]=false HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 146, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 186, in app
    solved_result = await solve_dependencies(
  File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 520, in solve_dependencies
    solved = await run_in_threadpool(call, **sub_values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/auth/service.py", line 82, in get_current_user
    return get_or_create(db_session=db_session, user_in=UserRegister(email=user_email))
  File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for UserRegister
email
  none is not an allowed value (type=type_error.none.not_allowed)
```

2) visiting `/incidents/report` for the first time always redirects to `/login`

3) `/login` redirects to the dashboard on successful login instead of back to the report page, which would confuse users who are just there to report issues.

4) Is there a way to separate users who are able to access the dashboard vs users who are able to report incidents?

**Comment by kevgliss** [comment]
> I've set DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic, I was running into issues with the Vue app not redirecting to /login until I realized I had to set VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG at container build time, as well. Even with this, /incidents/report fails to get Type and Priority because the JWT token is not sent to the API, even though it is present in local storage. It seems the Authorization header isn't being set correctly or in all places?

I've haven't been able to reproduce locally and will take a look.

> visiting /incidents/report for the first time always redirects to /login

I have been able to reproduce this and will take a look.

> /login redirects to the dashboard on successful login instead of back to the report page, which would confuse users who are just there to report issues.

We used to have the default route be /incidents/report but at the end of the day we don't really know why a user is hitting the UI (if they don't specify a route). Internally we use a URL shortener to help with guide users (something like `go/securityincident` so folks don't even have to know the dispatch URL. If you'd like to make the default configurable we'd be willing to merge that PR.

> Is there a way to separate users who are able to access the dashboard vs users who are able to report incidents?

Not today, Dispatch has a limited RBAC facilities that could be expanded but right now we allow folks mostly free-range (except when it comes to restricted incidents).

**Comment by bsundsrud** [comment]
I added a `console.log` to the interceptor in api.js that looks like it should intercept fetch requests and add the auth header, but it never fired on the /incidents/report page (first load, get types, get priorities seem like they should all have it?). Dashboard routes did trigger the logging/interceptor.

**Comment by kevgliss** [comment]
Can you see if https://github.com/Netflix/dispatch/pull/371 fixes your redirect issue?

**Comment by nitzango** [comment]
> > In order to get basic auth and before integrating the other plugin (Slack, Gsuite, Jira, etc) - Is it possible to have a running instance?
> 
> It is possible, yes, but you won't be able to create incidents as we don't have internal substitutes for all plugins yet. See #55
> 
> Some of the variables are interdependent, e.g. basic auth requires `DISPATCH_JWT_SECRET` but the other auth flows don't. If it helps we can try to break those up to make them clear. But server log will typically at least emit a warning stating if some interdependent configuration value is not set.

@mvilanova @kevgliss  - I got to a point that no matter what I do, even when starting from a fresh install I get this errors. Steps I did:

1. Clone the repo
2. Created .env and filled in all necessary details (GSuite, Slack and Jira)
3. Added `DISPATCH_JWT_SECRET` and `VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic` based on what the guys wrote
4. Ran `./install`
5. Accessed `<DISPATCH_ADDRESS/login` and logged in successfully
6. Browse to `<DISPATCH_ADDRESS/incidents/report` and then got these errors.


```
web_1        | INFO:     DEDACTED:63373 - "GET /api/v1/plugins/?q=&page=1&itemsPerPage=10&sortBy[]=slug&descending[]=true HTTP/1.1" 500 Internal Server Error
web_1        | ERROR:    Exception in ASGI application
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
web_1        |     result = await app(self.scope, self.receive, self.send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
web_1        |     return await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
web_1        |     await self.middleware_stack(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        |     await self.app(scope, receive, _send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        |     await response(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 222, in __call__
web_1        |     await run_until_first_complete(
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 214, in stream_response
web_1        |     async for chunk in self.body_iterator:
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        |     await response(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 222, in __call__
web_1        |     await run_until_first_complete(
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 214, in stream_response
web_1        |     async for chunk in self.body_iterator:
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        |     await response(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 222, in __call__
web_1        |     await run_until_first_complete(
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 214, in stream_response
web_1        |     async for chunk in self.body_iterator:
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        |     await self.app(scope, receive, sender)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
web_1        |     await route.handle(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 171, in __call__
web_1        |     await super().__call__(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
web_1        |     await self.middleware_stack(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        |     await self.app(scope, receive, _send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        |     await self.app(scope, receive, sender)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
web_1        |     await route.handle(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
web_1        |     response = await func(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 186, in app
web_1        |     solved_result = await solve_dependencies(
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 539, in solve_dependencies
web_1        |     solved = await run_in_threadpool(call, **sub_values)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
web_1        |     return await loop.run_in_executor(None, func, *args)
web_1        |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
web_1        |     result = self.fn(*self.args, **self.kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/auth/service.py", line 82, in get_current_user
web_1        |     return get_or_create(db_session=db_session, user_in=UserRegister(email=user_email))
web_1        |   File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
web_1        | pydantic.error_wrappers.ValidationError: 1 validation error for UserRegister
web_1        | email
web_1        |   none is not an allowed value (type=type_error.none.not_allowed)
web_1        | INFO:     82.81.195.5:63378 - "POST /api/v1/auth/login HTTP/1.1" 200 OK
web_1        | INFO:     82.81.195.5:63377 - "GET /api/v1/incident_priorities/ HTTP/1.1" 200 OK
web_1        | INFO:     82.81.195.5:63382 - "GET /api/v1/incidents/metric/forecast/all HTTP/1.1" 200 OK
web_1        | INFO:     82.81.195.5:63378 - "GET /api/v1/incident_types/?itemsPerPage=-1 HTTP/1.1" 200 OK
web_1        | INFO:     82.81.195.5:63383 - "GET /api/v1/incidents/?itemsPerPage=-1&sortBy[]=reported_at&descending[]=false&fields[]=reported_at&fields[]=reported_at&ops[]=%3E%3D&ops[]=%3C%3D&values[]=2019-12-28T22:00:00.000Z&values[]=2020-06-28T21:00:00.000Z HTTP/1.1" 200 OK
web_1        | INFO:     82.81.195.5:63383 - "GET /api/v1/plugins/?q=&page=1&itemsPerPage=10&sortBy[]=slug&descending[]=true HTTP/1.1" 200 OK
web_1        | INFO:     82.81.195.5:63383 - "GET /plugins HTTP/1.1" 200 OK
web_1        | INFO:     82.81.195.5:63383 - "GET /static/m.png HTTP/1.1" 200 OK
web_1        | INFO:     82.81.195.5:63386 - "GET /api/v1/plugins/?q=&page=1&itemsPerPage=10&sortBy[]=slug&descending[]=true HTTP/1.1" 500 Internal Server Error
web_1        | ERROR:    Exception in ASGI application
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
web_1        |     result = await app(self.scope, self.receive, self.send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
web_1        |     return await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
web_1        |     await self.middleware_stack(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        |     await self.app(scope, receive, _send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        |     await response(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 222, in __call__
web_1        |     await run_until_first_complete(
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 214, in stream_response
web_1        |     async for chunk in self.body_iterator:
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        |     await response(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 222, in __call__
web_1        |     await run_until_first_complete(
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 214, in stream_response
web_1        |     async for chunk in self.body_iterator:
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        |     await response(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 222, in __call__
web_1        |     await run_until_first_complete(
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 214, in stream_response
web_1        |     async for chunk in self.body_iterator:
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        |     await self.app(scope, receive, sender)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
web_1        |     await route.handle(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 171, in __call__
web_1        |     await super().__call__(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
web_1        |     await self.middleware_stack(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        |     await self.app(scope, receive, _send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        |     await self.app(scope, receive, sender)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
web_1        |     await route.handle(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
web_1        |     response = await func(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 186, in app
web_1        |     solved_result = await solve_dependencies(
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 539, in solve_dependencies
web_1        |     solved = await run_in_threadpool(call, **sub_values)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
web_1        |     return await loop.run_in_executor(None, func, *args)
web_1        |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
web_1        |     result = self.fn(*self.args, **self.kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/auth/service.py", line 82, in get_current_user
web_1        |     return get_or_create(db_session=db_session, user_in=UserRegister(email=user_email))
web_1        |   File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
web_1        | pydantic.error_wrappers.ValidationError: 1 validation error for UserRegister
web_1        | email
web_1        |   none is not an allowed value (type=type_error.none.not_allowed)

web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
```

**Comment by kevgliss** [comment]
Try setting:
 `DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic` 

instead of: 
`VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic`. 

You don't actually need to set the `VUE_APP_` as they just need to match:
https://github.com/Netflix/dispatch/blob/develop/src/dispatch/config.py#L79

Was there some documentation that made you think it needed to be set? If so, we should make that clearer.

**Comment by nitzango** [comment]
> Try setting:
> `DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic`
> 
> instead of:
> `VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic`.
> 
> You don't actually need to set the `VUE_APP_` as they just need to match:
> https://github.com/Netflix/dispatch/blob/develop/src/dispatch/config.py#L79
> 
> Was there some documentation that made you think it needed to be set? If so, we should make that clearer.

Thanks @kevgliss. I tried it and result is the same. 
When I'm logging in, I can see the dashboards filled with data (on homepage), but then after refresh it seems empty (like I was logged out) and then I get this error.

**Comment by kevgliss** [comment]
Okay, that helps, let me see if I can repo locally.

**Comment by kylie-sre** [comment]
@nitzango check that you're correctly sending the CORS headers to the Vue app. I encountered the same error as you and determined that the server wasn't sending the CORS headers I had configured with the `CORSMiddleware`. This was because the frontend code wasn't sending an `Origin` header with it's requests. By running the Vue app in one process with `npm run serve` and dispatch in another and accessing the Vue app in the browser solved the issue.

**Comment by santhoshparepu** [comment]
@kevgliss I see this issue is closed. I am also encountering the same issue as @nitzango. What is the resolution ?

**Comment by kevgliss** [comment]
@santhoshparepu a few things have changed since this was first reported, please open a new issue and we can debug there.

**Comment by santhoshparepu** [comment]
Thanks @kevgliss, I have opened https://github.com/Netflix/dispatch/issues/584.
