### ISSUE TITLE
Unable to load slack_contact and slack-conversations plugins on default install

### ISSUE THREAD

**Issue by jackblip** [Netflix/dispatch#362]
Hello, I am having some issues on running slack conversation and slack contact on dispatch with default configuration (nothing changed on .env file)
**Steps to reproduce:**
1. Clone dispatch-docker
2. rename .env.example to .env
2. Use default master branch or local path for docker develop branch  in docker-compose file
3. build image
4. run docker-compose 
5. dispatch is unable to load slack_conversation and slack_contact plugins 

```
scheduler_1  | ERROR:dispatch.common.utils.cli:Failed to load plugin slack_contact:Traceback (most recent call last):
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 34, in install_plugins
scheduler_1  |     plugin = ep.load()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in load
scheduler_1  |     return self.resolve()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2459, in resolve
scheduler_1  |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/plugin.py", line 37, in <module>
scheduler_1  |     from .views import router as slack_event_router
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/views.py", line 74, in <module>
scheduler_1  |     slack_client = dispatch_slack_service.create_slack_client()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 29, in create_slack_client
scheduler_1  |     return slack.WebClient(token=SLACK_API_BOT_TOKEN, run_async=run_async)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/slack/web/base_client.py", line 50, in __init__
scheduler_1  |     self.token = None if token is None else token.strip()
scheduler_1  | AttributeError: 'Secret' object has no attribute 'strip'
scheduler_1  | 
web_1        | ERROR:dispatch.common.utils.cli:Failed to load plugin slack_contact:Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 34, in install_plugins
web_1        |     plugin = ep.load()
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in load
web_1        |     return self.resolve()
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2459, in resolve
web_1        |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/plugin.py", line 37, in <module>
web_1        |     from .views import router as slack_event_router
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/views.py", line 74, in <module>
web_1        |     slack_client = dispatch_slack_service.create_slack_client()
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 29, in create_slack_client
web_1        |     return slack.WebClient(token=SLACK_API_BOT_TOKEN, run_async=run_async)
web_1        |   File "/usr/local/lib/python3.8/site-packages/slack/web/base_client.py", line 50, in __init__
web_1        |     self.token = None if token is None else token.strip()
web_1        | AttributeError: 'Secret' object has no attribute 'strip'
web_1        | 
scheduler_1  | ERROR:dispatch.common.utils.cli:Failed to load plugin slack_conversation:Traceback (most recent call last):
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 34, in install_plugins
scheduler_1  |     plugin = ep.load()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in load
scheduler_1  |     return self.resolve()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2459, in resolve
scheduler_1  |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/plugin.py", line 37, in <module>
scheduler_1  |     from .views import router as slack_event_router
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/views.py", line 74, in <module>
scheduler_1  |     slack_client = dispatch_slack_service.create_slack_client()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 29, in create_slack_client
scheduler_1  |     return slack.WebClient(token=SLACK_API_BOT_TOKEN, run_async=run_async)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/slack/web/base_client.py", line 50, in __init__
scheduler_1  |     self.token = None if token is None else token.strip()
scheduler_1  | AttributeError: 'Secret' object has no attribute 'strip'
scheduler_1  | 
web_1        | ERROR:dispatch.common.utils.cli:Failed to load plugin slack_conversation:Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 34, in install_plugins
web_1        |     plugin = ep.load()
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in load
web_1        |     return self.resolve()
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2459, in resolve
web_1        |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/plugin.py", line 37, in <module>
web_1        |     from .views import router as slack_event_router
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/views.py", line 74, in <module>
web_1        |     slack_client = dispatch_slack_service.create_slack_client()
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 29, in create_slack_client
web_1        |     return slack.WebClient(token=SLACK_API_BOT_TOKEN, run_async=run_async)
web_1        |   File "/usr/local/lib/python3.8/site-packages/slack/web/base_client.py", line 50, in __init__
web_1        |     self.token = None if token is None else token.strip()
web_1        | AttributeError: 'Secret' object has no attribute 'strip'
web_1        | 
scheduler_1  | WARNING:dispatch.common.utils.cli:Failed to load plugin: zoom_conference Reason: "Config 'ZOOM_API_USER_ID' is missing, and has no default."
web_1        | WARNING:dispatch.common.utils.cli:Failed to load plugin: zoom_conference Reason: "Config 'ZOOM_API_USER_ID' is missing, and has no default."
scheduler_1  | Starting scheduler...
web_1        | INFO:     Started server process [1]
web_1        | INFO:     Waiting for application startup.
web_1        | INFO:     Application startup complete.
web_1        | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

```

Any ideas how this could be mitigated? 
Thank you.

**Comment by jackblip** [comment]
managed to fixit by specifiying slackclient version in dispatch/requirements.base file to use 2.5.0

`slackclient==2.5.0`

**Comment by kevgliss** [comment]
I've open up a PR to explicitly pass string objects to the slack client instead of secret objects. This should allow us to use newer slackclient versions. Thanks for the report.
