### ISSUE TITLE
Create incident from slack fails if "Type" not provided

### ISSUE THREAD

**Issue by mrpea** [Netflix/dispatch#3708]
**Describe the bug**
Creating an incident from Slack fails if the user does not pick a Type from the dropdown.

**To Reproduce**
* `/dispatch-report-incident`
* Fill out title, description, and Project.
* Hit "Report"
* Get error :/ 

**Expected behavior**
Either the Type is marked as required (and the submit button is disabled) or type is allowed to be null

**Screenshots**

<img width="641" alt="Screenshot 2023-08-18 at 4 05 32 PM" src="https://github.com/Netflix/dispatch/assets/1892535/2d20fece-c4c2-4ceb-9ad9-17eee6156cf1">

**Additional context**
Log files show this:
```
ERROR:slack_bolt.App:1 validation error for IncidentTypeRead
incident_type
  No default incident type defined. (type=value_error.not_found; msg=No default incident type defined.)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dispatch/plugins/dispatch_slack/incident/interactive.py", line 1976, in handle_report_incident_submission_event
    incident = incident_service.create(db_session=db_session, incident_in=incident_in)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dispatch/incident/service.py", line 157, in create
    incident_type = incident_type_service.get_by_name_or_default(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dispatch/incident/type/service.py", line 88, in get_by_name_or_default
    return get_default_or_raise(db_session=db_session, project_id=project_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dispatch/incident/type/service.py", line 33, in get_default_or_raise
    raise ValidationError(
```

**Comment by whitdog47** [comment]
Hi @mrpea - when you go to "Settings", click on your Project name. Then on the submenu pane there is a section for Incident->Types. Please make sure that one of these Types is set as the default. Then you shouldn't see this error.
