### ISSUE TITLE
Installation instructions outside of docker ?

### ISSUE THREAD

**Issue by chapmanjacobd** [Netflix/dispatch#459]
**Is your feature request related to a problem? Please describe.**
I would like to install this on AppEngine Standard but I'm not too familiar with python

**Describe the solution you'd like**
I think this should be possible. I've already pre-built the Vue static files so I won't need to run node in AppEngine

```sh
cd src/dispatch/static/dispatch
npx vue-cli-service build
```

I'm pretty sure connecting to CloudSQL is like this: 

```bash
$ tee .env
DATABASE_CREDENTIALS=CLOUD_SQL_USERNAME:CLOUD_SQL_PASSWORD
DATABASE_HOSTNAME=localhost
DATABASE_NAME=CLOUD_SQL_DATABASE_NAME?unix_socket=/cloudsql/CLOUD_SQL_CONNECTION_NAME
DATABASE_PORT=5432
```

I'm using this entrypoint:

```
entrypoint: python setup.py bdist_wheel && dispatch server start dispatch.main:app
```

but I get the error: 

```error
invalid command 'bdist_wheel'
```

Is there anything else that I need to be aware of ?

thanks

**Comment by kevgliss** [comment]
Perhaps you need the `wheel` package?

See: https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci

**Comment by chapmanjacobd** [comment]
Do you think it is possible to run this without `sudo` being a requirement? It looks like system-level packages are not supported on AppEngine either. Maybe I will need to modify setup.py to make it more stateless...

if you were setting this up outside of docker what would the steps be ? 

```
pipenv install -r requirements.txt
...?
```

**Comment by kevgliss** [comment]
On a macro level it's just a python app, so any tutorials on installing python apps would be relevant, I haven't deployed to app engine before so I'm not sure if its particular quirks. I think you're on the right path, for example to run on my local Linux machine the steps are basically:

`git clone git@github.com:Netflix/dispatch.git`
`cd dispatch`
`pip install -e .`

and then to run the server:

`dispatch server start`

You don't _need_ to create venv for the project, but it is recommended for python projects to avoid conflicting dependencies.

**Comment by chapmanjacobd** [comment]
```
git clone git@github.com:Netflix/dispatch.git
cd dispatch
python setup.py build

```

If I use this as my entrypoint `python setup.py install && dispatch server start` on AppEngine then I get 

```
[Errno 30] Read-only file system: '/env/lib/python3.7/site-packages/test-easy-install-12.write-test'"
```

It looks like AppEngine will only support installing via `requirements.txt` so I added `./` to requirements.txt (copied from requirements-base.txt:

I get this error message:

```
Step #1 - "builder": Successfully built SQLAlchemy-Searchable alembic pypd python-multipart sentry-asgi SQLAlchemy-Utils validators wasabi
Step #1 - "builder": Failed to build dispatch
Step #1 - "builder": 
Step #1 - "builder": INFO     `pip_download_wheels` had stderr output:
Step #1 - "builder":   ERROR: Command errored out with exit status 1:
Step #1 - "builder":    command: /env/bin/python3.7 /env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpbpqt0rw9
Step #1 - "builder":        cwd: /tmp/pip-req-build-w_ph5i_1
Step #1 - "builder":   Complete output (5 lines):
Step #1 - "builder":   running bdist_wheel
Step #1 - "builder":   running build
Step #1 - "builder":   running build_assets
Step #1 - "builder":   command failed [node --version] via [/tmp/pip-req-build-w_ph5i_1/src/dispatch/static/dispatch]
Step #1 - "builder":   Cannot find node executable. Please install node and try again.
Step #1 - "builder":   ----------------------------------------
Step #1 - "builder":   ERROR: Failed building wheel for dispatch
Step #1 - "builder": ERROR: Failed to build one or more wheels
Step #1 - "builder": 
Step #1 - "builder": ERROR    error: `pip_download_wheels` returned code: 1
Step #1 - "builder": INFO     pip_download_wheels took 24 seconds
Step #1 - "builder": INFO     build process for FTL image took 28 seconds
Step #1 - "builder": INFO     full build took 28 seconds
Step #1 - "builder": ERROR    `pip_download_wheels` had stderr output:
Step #1 - "builder":   ERROR: Command errored out with exit status 1:
Step #1 - "builder":    command: /env/bin/python3.7 /env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpbpqt0rw9
Step #1 - "builder":        cwd: /tmp/pip-req-build-w_ph5i_1
Step #1 - "builder":   Complete output (5 lines):
Step #1 - "builder":   running bdist_wheel
Step #1 - "builder":   running build
Step #1 - "builder":   running build_assets
Step #1 - "builder":   command failed [node --version] via [/tmp/pip-req-build-w_ph5i_1/src/dispatch/static/dispatch]
Step #1 - "builder":   Cannot find node executable. Please install node and try again.
Step #1 - "builder":   ----------------------------------------
Step #1 - "builder":   ERROR: Failed building wheel for dispatch
Step #1 - "builder": ERROR: Failed to build one or more wheels
Step #1 - "builder": 
Step #1 - "builder": error: `pip_download_wheels` returned code: 1
Step #1 - "builder": Traceback (most recent call last):
Step #1 - "builder":   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Step #1 - "builder":     "__main__", fname, loader, pkg_name)
Step #1 - "builder":   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Step #1 - "builder":     exec code in run_globals
Step #1 - "builder":   File "/usr/local/bin/ftl.par/__main__.py", line 65, in <module>
Step #1 - "builder":   File "/usr/local/bin/ftl.par/__main__.py", line 57, in main
Step #1 - "builder":   File "/usr/local/bin/ftl.par/__main__/ftl/common/ftl_error.py", line 58, in UserErrorHandler
Step #1 - "builder": IOError: [Errno 2] No such file or directory: '""/output'
```

I think I'm pretty close to getting it working. I removed `self._setup_js_deps()` from `setup.py`

```
Step #1 - "builder":   ERROR: Command errored out with exit status 1:
Step #1 - "builder":    command: /env/bin/python3.7 /env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmprpebccgv
Step #1 - "builder":        cwd: /tmp/pip-req-build-9gz5ohr4
Step #1 - "builder":   Complete output (6 lines):
Step #1 - "builder":   running bdist_wheel
Step #1 - "builder":   running build
Step #1 - "builder":   running build_assets
Step #1 - "builder":   pulled version information from 'dispatch' module. /tmp/pip-req-build-9gz5ohr4/src/dispatch/__init__.py
Step #1 - "builder":   building assets for dispatch v0.1.0.dev0 (build UNKNOWN)
Step #1 - "builder":   Could not determine dispatch version or build
```

so I removed `self._setup_git()` and changed _get_package_version() build variable to a constant string

okay now it seems to be working :)
