### ISSUE TITLE
Error with opsgenie_oncall and jira_ticket during stock install

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch#591]
**Describe the bug**
ONCALL_PLUGIN_SLUG currently defaults to `opsgenie-oncall` if there is no other slug defined. This causes an error after stock installation even if pagerduty values are otherwise configured. 

**Suggested fix**
- Add a section to configuring-slack.md that calls out needing to change `ONCALL_PLUGIN_SLUG=pagerduty-oncall`
- declare and briefly explain `ONCALL_PLUGIN_SLUG` in app.md

**Comment by kevgliss** [comment]
What error where you experiencing? afaik with the latest builds we don't require any `oncall` plugins be enabled (will default to the reporter). 

It _does_ look like we have some old references to that config item we need to remove though:
https://github.com/Netflix/dispatch/search?q=ONCALL_PLUGIN_SLUG

**Comment by alexa-kelley-vim** [comment]
Oh that's really good to know. Here is an example of the error I came across. For some reason when the install script runs 
`docker-compose run web plugins install` then both the opsgenie_oncall and jira plugin throw an error. 

`Setting up database...
Do you want to load example data (y/n)?n
Starting dispatch_postgres_1 ... done
No metric providers specified metrics will not be sent.
ERROR:dispatch.common.utils.cli:Failed to load plugin jira_ticket:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_jira/plugin.py", line 15, in <module>
    from .config import (
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_jira/config.py", line 6, in <module>
    JIRA_BROWSER_URL = config("JIRA_BROWSER_URL", cast=URL)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'JIRA_BROWSER_URL' is missing, and has no default."

ERROR:dispatch.common.utils.cli:Failed to load plugin opsgenie_oncall:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/plugin.py", line 11, in <module>
    from .service import get_oncall, page_oncall
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/service.py", line 4, in <module>
    from .config import OPSGENIE_API_KEY, OPSGENIE_TEAM_ID
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/config.py", line 4, in <module>
    OPSGENIE_API_KEY = config("OPSGENIE_API_KEY", cast=Secret)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'OPSGENIE_API_KEY' is missing, and has no default."

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Success.

Installing plugins...
Starting dispatch_postgres_1 ... done
No metric providers specified metrics will not be sent.
ERROR:dispatch.common.utils.cli:Failed to load plugin jira_ticket:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_jira/plugin.py", line 15, in <module>
    from .config import (
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_jira/config.py", line 6, in <module>
    JIRA_BROWSER_URL = config("JIRA_BROWSER_URL", cast=URL)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'JIRA_BROWSER_URL' is missing, and has no default."

ERROR:dispatch.common.utils.cli:Failed to load plugin opsgenie_oncall:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/plugin.py", line 11, in <module>
    from .service import get_oncall, page_oncall
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/service.py", line 4, in <module>
    from .config import OPSGENIE_API_KEY, OPSGENIE_TEAM_ID
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/config.py", line 4, in <module>
    OPSGENIE_API_KEY = config("OPSGENIE_API_KEY", cast=Secret)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'OPSGENIE_API_KEY' is missing, and has no default."

Installing plugin... Slug: dispatch-auth-provider-basic Version: 0.1.0
Installing plugin... Slug: dispatch-contact Version: 0.1.0
Installing plugin... Slug: dispatch-document-resolver Version: 0.1.0
Installing plugin... Slug: dispatch-auth-provider-pkce Version: 0.1.0
Installing plugin... Slug: dispatch-participant-resolver Version: 0.1.0
Installing plugin... Slug: dispatch-ticket Version: 0.1.0
Installing plugin... Slug: google-calendar-conference Version: 0.1.0
Installing plugin... Slug: google-docs-document Version: 0.1.0
Installing plugin... Slug: google-drive-storage Version: 0.1.0
Installing plugin... Slug: google-drive-task Version: 0.1.0
Installing plugin... Slug: google-gmail-email Version: 0.1.0
Installing plugin... Slug: google-group-participant-group Version: 0.1.0
Installing plugin... Slug: pagerduty-oncall Version: 0.1.0
Installing plugin... Slug: slack-contact Version: 0.1.0
Installing plugin... Slug: slack-conversation Version: 0.1.0
Installing plugin... Slug: zoom-conference Version: 0.1.0
Cleaning up...`

**Comment by alexa-kelley-vim** [comment]
Also from a stock install running dispatch at root (inside web container) throws the following error, which looks like it's still trying to access those plugins. 

```
/# dispatch
No metric providers specified metrics will not be sent.
ERROR:dispatch.common.utils.cli:Failed to load plugin jira_ticket:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_jira/plugin.py", line 15, in <module>
    from .config import (
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_jira/config.py", line 6, in <module>
    JIRA_BROWSER_URL = config("JIRA_BROWSER_URL", cast=URL)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'JIRA_BROWSER_URL' is missing, and has no default."

ERROR:dispatch.common.utils.cli:Failed to load plugin opsgenie_oncall:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/plugin.py", line 11, in <module>
    from .service import get_oncall, page_oncall
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/service.py", line 4, in <module>
    from .config import OPSGENIE_API_KEY, OPSGENIE_TEAM_ID
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/config.py", line 4, in <module>
    OPSGENIE_API_KEY = config("OPSGENIE_API_KEY", cast=Secret)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'OPSGENIE_API_KEY' is missing, and has no default."

Usage: dispatch [OPTIONS] COMMAND [ARGS]...

  Command-line interface to Dispatch.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  database   Container for all dispatch database commands.
  plugins    All commands for plugin manipulation.
  scheduler  Container for all dispatch scheduler commands.
  server     Container for all dispatch server commands.
```

**Comment by alexa-kelley-vim** [comment]
This is just a guess, but it looks like ./dispatch/src/config.py still has

`ONCALL_PLUGIN_SLUG = config("ONCALL_PLUGIN_SLUG", default="opsgenie-oncall")`

which _maybe_ could be causing the opsgenie error? I'll try a test run to see if omitting it fixes it.

**Comment by kevgliss** [comment]
Both of those errors should really just be warnings. I accidentally changed the log level on them, I will change them back. They are used to simply say that the plugin couldn't be installed because you were missing config values for them. Not that you _need_ to have them installed (as all plugins are optional). 

Once they are warnings (instead of errors) they shouldn't show up on every command.

**Comment by kevgliss** [comment]
Is this annoying you? I can push out a release with the fixes or I will wait till the next major release (probably a week away).

**Comment by alexa-kelley-vim** [comment]
No not bugging me, you can go ahead and push it with the next release. Thank you :)
