### ISSUE TITLE
Can't create first user after fresh installation

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/dispatch#778]
**Describe the bug**
I'm unable to create a new account and experience numerous 500 errors from the server. When investigating the logs, I see the following error: 

```
web_1        | KeyError: 'dispatch-auth-provider-basic'
web_1        | ERROR:uvicorn.error:Exception in ASGI application
```

Reloading the page does nothing for me and I still receive 500 errors.

**To Reproduce**

1. Do a fresh install utilizing Dispatch docker's install.sh (pulled latest version on github as of 1/16). Please note I ran into a separate issue with install.sh. I've circumvented this particular issue with doing `dispatch database init; dispatch database upgrade` in the dispatch web docker instance after install.sh completed. I've intentionally left the details of this separate issue from this ticket but am happy to provide more details if needed.

2. Once installed, visit `/auth/register` and create a new user. Here I received 200's from both the /register and /login endpoints.

![Screen Shot 2021-01-16 at 4 46 19 PM](https://user-images.githubusercontent.com/52643283/104823740-6dd4f900-581a-11eb-9eef-a3088e15b27d.png)

3. I am then redirected to the dashboard but am receiving various 500 errors. See the screenshot above.

**Expected behavior**
I should not be receiving 500 errors.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Browser Firefox
 - Version 84.0.2

**Additional context**
I investigated the logs produced by the web docker instance. I've posted it in this gist [here](https://gist.github.com/mrthankyou/71a7300a6b0fda72ea5d1cdab49ef1b6). It looks like the error is dealing with an authentication issue. I haven't dug into the code to know where the issue is occurring. It's effectively prevented me from testing this application. Any help on this would be appreciated and I'm happy to provide anymore info.

**Comment by kevgliss** [comment]
Would you be able to list the installed plugins via `dispatch plugins list`? 

Judging from your network request you are able to /login and /register ? Is that right?

**Comment by mrthankyou** [comment]
I'll be testing this issue again with the #782 fix and report back the results.

**Comment by kevgliss** [comment]
I think I found a different dep issue. Looking now...

**Comment by mrthankyou** [comment]
Ok, when I get a chance tonight I'll send you the `dispatch plugins list` output.

**Comment by kevgliss** [comment]
I believe between the fixes for #782, #783 and #784 we should be in better shape. Please let me know if that's not the case.

**Comment by mrthankyou** [comment]
I just ran the `dispatch plugins list` and it's reporting that I have no plugins with a whole bunch of errors (see output below). 

I'll pull again tomorrow and see if that fixes everything. Thanks for resolving these issues!

```
# dispatch plugins list
ERROR:dispatch.common.utils.cli:Failed to load plugin dispatch_basic_auth:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin dispatch_contact:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin dispatch_document_resolver:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin dispatch_participant_resolver:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin dispatch_pkce_auth:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin dispatch_ticket:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin google_calendar_conference:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin google_docs_document:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin google_drive_storage:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin google_drive_task:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin google_gmail_email:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin google_groups_participants:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin jira_ticket:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin opsgenie_oncall:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin pagerduty_oncall:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin slack_contact:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin slack_conversation:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

ERROR:dispatch.common.utils.cli:Failed to load plugin zoom_conference:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('chardet<4.0,>=2.0'), {'aiohttp'})

Title    Slug    Version    Enabled    Type    Author    Description
-------  ------  ---------  ---------  ------  --------  -------------
# 

```

**Comment by mrthankyou** [comment]
@kevgliss 

Proud to say everything is working! I'm happy with closing the issue if you are!
