### ISSUE TITLE
Database migration error

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Netflix/dispatch#779]
**Describe the bug**
Seems like there is an error while trying to execute the migration to the latest version of the database.

```bash
INFO:Context impl PostgresqlImpl.:/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py:__init__:155
--
INFO:Will assume transactional DDL.:/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py:__init__:158
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 1c3f808aa00c -> 38f0b01448ba, Adds on delete cascade behavior and renames primary and foreign keys, and sequence id for report
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "status_report_pkey" does not exist
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/bin/dispatch", line 8, in <module>
sys.exit(entrypoint())
File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 606, in entrypoint
dispatch_cli()
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 350, in upgrade_database
alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
script.run_env()
File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
util.load_python_file(self.dir, "env.py")
File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
module = load_module_py(module_id, path)
File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 83, in <module>
run_migrations_online()
File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 77, in run_migrations_online
context.run_migrations()
File "<string>", line 8, in run_migrations
File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
self.get_context().run_migrations(**kw)
File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 522, in run_migrations
step.migration_fn(**kw)
File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/versions/38f0b01448ba_.py", line 22, in upgrade
bind.execute("ALTER INDEX status_report_pkey RENAME TO report_pkey")
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
return self._execute_text(object_, multiparams, params)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
ret = self._execute_context(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "status_report_pkey" does not exist
[SQL: ALTER INDEX status_report_pkey RENAME TO report_pkey]
(Background on this error at: http://sqlalche.me/e/13/f405)
```
And I found that report_pkey already exists.
![image](https://user-images.githubusercontent.com/72515998/104958655-464e6f80-5985-11eb-8d00-1a0b4a6d4a90.png)

**To Reproduce**
1. `git pull` # pull latest master
2. Run database upgrade on the `dispatch_web` container

To reproduce locally:
1. Run `install.sh`
2. At the prompt to load example chose: n
3. See error.

**Expected behavior**
We expect the latest model to be setup when we run `dispatch database upgrade` irrespective of which version of the data model we have currently on the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/72515998/104958655-464e6f80-5985-11eb-8d00-1a0b4a6d4a90.png)

**Comment by mvilanova** [comment]
Thanks for the report. I know what the issue is. I'll cut a PR to fix it today.

**Comment by mvilanova** [comment]
@sfc-gh-pkommini #780 should fix it. Let me know if you run into any other issues.

**Comment by sfc-gh-pkommini** [comment]
Gave me some other issues but since we don't have production data yet. I just did a fresh database setup.
