### ISSUE TITLE
Slack Socket Mode code cause application break

### ISSUE THREAD

**Issue by rilutham** [Netflix/dispatch#806]
**Describe the bug**
After pulling the latest code from the master branch that contains Slack socket mode, the application cannot start. Previously, I was using Slack event mode and already set the following env:
- SLACK_SIGNING_SECRET
- SLACK_API_BOT_TOKEN

**To Reproduce**
1. Pull the latest code from commit 7cce8b7a9f3c2e051ba7472a9846fd6ab6787a23 
2. Deploy on my server
3. Application cannot start

**Expected behavior**
Application starts with Slack Event mode enabled and working as usual.

**Error From Server Log**
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 25, in <module>
from aiohttp import __version__ as AIOHTTP_VERSION
ModuleNotFoundError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/bin/dispatch", line 5, in <module>
from dispatch.cli import entrypoint
File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 15, in <module>
from .main import *  # noqa
File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 20, in <module>
from .extensions import configure_extensions
File "/usr/local/lib/python3.8/site-packages/dispatch/extensions.py", line 5, in <module>
from sentry_sdk.integrations.aiohttp import AioHttpIntegration
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 28, in <module>
raise DidNotEnable("AIOHTTP not installed")
sentry_sdk.integrations.DidNotEnable: AIOHTTP not installed
```

**Comment by sfc-gh-pkommini** [comment]
I got this error as well. I was able to fix it by adding aiohttp to the `requirements-base.txt` file.

**Comment by sfc-gh-pkommini** [comment]
I think slackclient was using `aiohttp` and hence it was transitively imported and now has to be explicitly imported. Just a guess.

**Comment by kevgliss** [comment]
Yes, it seems that aiohttp is now an optional dependency of `slack_sdk` where in `slackclient` it was a required dependency. I will get this added the the requirements file.
