### ISSUE TITLE
slack slash command /dispatch-add-timeline-event

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Netflix/dispatch#812]
**Describe the bug**
When performing the slack slash command `/dispatch-add-timeline-event`, I get the following error:
![image](https://user-images.githubusercontent.com/72515998/106204121-4ca4ce80-6171-11eb-9cbb-b9ebcdd1923d.png)

The logs has this message, Would you know what could cause this? I'm think it maybe a user resolver plugin issue or something.

```
INFO:    <IP redacted>:<port redacted>- "POST /api/v1/events/slack/action HTTP/1.1" 500 Internal Server Error
--
ERROR:    Exception in ASGI application
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
await self.app(scope, receive, _send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
await response(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
await run_until_first_complete(
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
async for chunk in self.body_iterator:
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
task.result()
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
await response(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
await run_until_first_complete(
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
async for chunk in self.body_iterator:
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
task.result()
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
await response(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
await run_until_first_complete(
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
async for chunk in self.body_iterator:
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
task.result()
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
await self.app(scope, receive, sender)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
await route.handle(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
await super().__call__(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
await self.app(scope, receive, _send)
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
await self.app(scope, receive, sender)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
await route.handle(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
response = await func(request)
File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
raw_response = await run_endpoint_function(
File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
return await dependant.call(**values)
File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/views.py", line 169, in handle_action
return await handle_slack_action(
File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/actions.py", line 33, in handle_slack_action
user_email = dispatch_slack_service.get_user_email(client, user_id)
File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 207, in get_user_email
user_info = get_user_info_by_id(client, user_id)
File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 180, in get_user_info_by_id
return make_call(client, "users.info", user=user_id)["user"]
TypeError: 'coroutine' object is not subscriptable
ERROR:Exception in ASGI application
:/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py:run_asgi:397
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
await self.app(scope, receive, _send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
await response(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
await run_until_first_complete(
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
async for chunk in self.body_iterator:
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
task.result()
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
await response(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
await run_until_first_complete(
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
async for chunk in self.body_iterator:
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
task.result()
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
await response(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
await run_until_first_complete(
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
[task.result() for task in done]
File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
async for chunk in self.body_iterator:
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
task.result()
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
await self.app(scope, receive, sender)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
await route.handle(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
await super().__call__(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
await self.app(scope, receive, _send)
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
raise exc from None
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
await self.app(scope, receive, sender)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
await route.handle(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
response = await func(request)
File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
raw_response = await run_endpoint_function(
File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
return await dependant.call(**values)
File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/views.py", line 169, in handle_action
return await handle_slack_action(
File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/actions.py", line 33, in handle_slack_action
user_email = dispatch_slack_service.get_user_email(client, user_id)
File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 207, in get_user_email
user_info = get_user_info_by_id(client, user_id)
File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 180, in get_user_info_by_id
return make_call(client, "users.info", user=user_id)["user"]
TypeError: 'coroutine' object is not subscriptable
```

**Comment by mvilanova** [comment]
I think I know what the issue is. I'll put out a fix for it.
