### ISSUE TITLE
Cannot report an incident from Slack

### ISSUE THREAD

**Issue by rilutham** [Netflix/dispatch#833]
**Describe the bug**
Cannot report an incident from Slack using the `/dispatch-report-incident` slash command.

**To Reproduce**
1. In Slack, execute the `/dispatch-report-incident`
2. Slackbot return an error `/dispatch-report-incident failed with the error "operation_timeout"`

**Error log**
```
ERROR:dispatch.plugins.dispatch_slack.service:SlackError. Response: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] `trigger_id` expired [json-pointer:/trigger_id]']}} Endpoint: views.open kwargs: {'trigger_id': '1714578994995.22999497858.abe565e54fd4250c682e61071bc03048', 'view': {'type': 'modal', 'title': {'type': 'plain_text', 'text': 'Security Incident Report'}, 'blocks': [{'type': 'context', 'elements': [{'type': 'mrkdwn', 'text': 'If you suspect a security incident and require help from security, please fill out the following to the best of your abilities.'}]}, {'block_id': <IncidentSlackViewBlockId.title: 'title_field'>, 'type': 'input', 'label': {'type': 'plain_text', 'text': 'Title'}, 'element': {'type': 'plain_text_input', 'placeholder': {'type': 'plain_text', 'text': 'A brief explanatory title. You can change this later.'}}}, {'block_id': <IncidentSlackViewBlockId.description: 'description_field'>, 'type': 'input', 'label': {'type': 'plain_text', 'text': 'Description'}, 'element': {'type': 'plain_text_input', 'placeholder': {'type': 'plain_text', 'text': "A summary of what you know so far. It's all right if this is incomplete."}, 'multiline': True}}, {'block_id': <IncidentSlackViewBlockId.type: 'incident_type_field'>, 'type': 'input', 'label': {'type': 'plain_text', 'text': 'Type'}, 'element': {'type': 'static_select', 'placeholder': {'type': 'plain_text', 'text': 'Select Incident Type'}, 'options': [{'text': {'type': 'plain_text', 'text': 'Vulnerability', 'emoji': True}, 'value': 'Vulnerability'}]}}, {'block_id': <IncidentSlackViewBlockId.priority: 'incident_priority_field'>, 'type': 'input', 'label': {'type': 'plain_text', 'text': 'Priority', 'emoji': True}, 'element': {'type': 'static_select', 'placeholder': {'type': 'plain_text', 'text': 'Select Incident Priority'}, 'options': [{'text': {'type': 'plain_text', 'text': 'Low', 'emoji': True}, 'value': 'Low'}, {'text': {'type': 'plain_text', 'text': 'Medium', 'emoji': True}, 'value': 'Medium'}, {'text': {'type': 'plain_text', 'text': 'High', 'emoji': True}, 'value': 'High'}]}}], 'close': {'type': 'plain_text', 'text': 'Cancel'}, 'submit': {'type': 'plain_text', 'text': 'Submit'}, 'callback_id': <NewIncidentSubmission.form_slack_view: 'submit-new-incident-form-from-slack'>, 'private_metadata': '{"channel_id": "xxxxxxx"}'}}
```

**Comment by mvilanova** [comment]
Can you share the full stacktrace? I think it's also related to the issue with create_message_blocks()

**Comment by rilutham** [comment]
I think it is a different root cause @mvilanova , here is the following trace:

```

 ERROR:dispatch.plugins.dispatch_slack.service:SlackError. Response: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] `trigger_id` expired [json-pointer:/trigger_id]']}} Endpoint: views.open kwargs: {'trigger_id': '1721914625122.22999497858.34a0788bb4903f2894e8d2fdccafb9ab', 'view': {'type': 'modal', 'title': {'type': 'plain_text', 'text': 'Security Incident Report'}, 'blocks': [{'type': 'context', 'elements': [{'type': 'mrkdwn', 'text': 'If you suspect a security incident and require help from security, please fill out the following to the best of your abilities.'}]}, {'block_id': <IncidentSlackViewBlockId.title: 'title_field'>, 'type': 'input', 'label': {'type': 'plain_text', 'text': 'Title'}, 'element': {'type': 'plain_text_input', 'placeholder': {'type': 'plain_text', 'text': 'A brief explanatory title. You can change this later.'}}}, {'block_id': <IncidentSlackViewBlockId.description: 'description_field'>, 'type': 'input', 'label': {'type': 'plain_text', 'text': 'Description'}, 'element': {'type': 'plain_text_input', 'placeholder': {'type': 'plain_text', 'text': "A summary of what you know so far. It's all right if this is incomplete."}, 'multiline': True}}, {'block_id': <IncidentSlackViewBlockId.type: 'incident_type_field'>, 'type': 'input', 'label': {'type': 'plain_text', 'text': 'Type'}, 'element': {'type': 'static_select', 'placeholder': {'type': 'plain_text', 'text': 'Select Incident Type'}, 'options': [{'text': {'type': 'plain_text', 'text': 'Vulnerability', 'emoji': True}, 'value': 'Vulnerability'}]}}, {'block_id': <IncidentSlackViewBlockId.priority: 'incident_priority_field'>, 'type': 'input', 'label': {'type': 'plain_text', 'text': 'Priority', 'emoji': True}, 'element': {'type': 'static_select', 'placeholder': {'type': 'plain_text', 'text': 'Select Incident Priority'}, 'options': [{'text': {'type': 'plain_text', 'text': 'Low', 'emoji': True}, 'value': 'Low'}, {'text': {'type': 'plain_text', 'text': 'Medium', 'emoji': True}, 'value': 'Medium'}, {'text': {'type': 'plain_text', 'text': 'High', 'emoji': True}, 'value': 'High'}]}}], 'close': {'type': 'plain_text', 'text': 'Cancel'}, 'submit': {'type': 'plain_text', 'text': 'Submit'}, 'callback_id': <NewIncidentSubmission.form_slack_view: 'submit-new-incident-form-from-slack'>, 'private_metadata': '{"channel_id": "C01KK9UQNTX"}'}}
 ERROR:dispatch.decorators:The request to the Slack API failed.
 The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] `trigger_id` expired [json-pointer:/trigger_id]']}}
 Traceback (most recent call last):
 result = func(*args, **kwargs)
 File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/modals.py", line 306, in create_report_incident_modal
 dispatch_slack_service.open_modal_with_user(
 File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 418, in open_modal_with_user
 return make_call(client, "views.open", trigger_id=trigger_id, view=modal)
 File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 333, in wrapped_f
 return self(f, *args, **kw)
 File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 423, in __call__
 do = self.iter(retry_state=retry_state)
 File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 360, in iter
 return fut.result()
 File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
 return self.__get_result()
 File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
 raise self._exception
 File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 426, in __call__
 result = fn(*args, **kwargs)
 File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 139, in make_call
 raise e
 File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 115, in make_call
 response = client.api_call(endpoint, json=kwargs)
 File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 128, in api_call
 return self._sync_send(api_url=api_url, req_args=req_args)
 File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 164, in _sync_send
 return self._urllib_api_call(
 File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 292, in _urllib_api_call
 return SlackResponse(
 File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/slack_response.py", line 201, in validate
 raise e.SlackApiError(message=msg, response=self)
 slack_sdk.errors.SlackApiError: The request to the Slack API failed.
 The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] `trigger_id` expired [json-pointer:/trigger_id]']}}
 ```

**Comment by mvilanova** [comment]
Looks like there was enough big of a delay between when you received the `trigger_id` and when it was sent to Slack, triggering this error. This shouldn't happen if you have good connectivity.

From https://api.slack.com/interactivity/handling#modal_responses:
> Triggers expire in three seconds. Use them before you lose them. You'll receive a trigger_expired error when using a method with an expired trigger_id.

**Comment by rilutham** [comment]
Understood @mvilanova
