### ISSUE TITLE
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "status_report_pkey" does not exist

### ISSUE THREAD

**Issue by dk0r** [Netflix/dispatch#842]
### Describe the bug

**Dispatch** fails to start when utilizing [`install.sh`](https://github.com/Netflix/dispatch-docker/blob/master/install.sh) from [`dispatch-docker@28b90d0`](https://github.com/Netflix/dispatch-docker/commit/28b90d0ea78bc8c92435aacc4f52136f142e996c)

Upon executing [`install.sh`](https://github.com/Netflix/dispatch-docker/blob/master/install.sh) and later responding to whether or not to load example data, the following error is incurred:
`sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "status_report_pkey" does not exist`

### To Reproduce
1. `$ git clone https://github.com/Netflix/dispatch-docker.git && cd dispatch-docker`
2. `$ ./install.sh`
3. Respond `y` or `N` to the following inquiry --note: the same error is ultimately incurred regardless of the response chosen
    ```
    Do you want to load example data (WARNING: this will remove all existing database data) (y/N)?
    ```

### Expected behavior
 1. **Dispatch** and it's **dependencies** are running in containers identified by doing `docker container ls`
 2. **Dispatch UI** is accessible at `http://localhost:8000/auth/register`

### Logs

* **Full** logs 👉  [ output.txt](https://github.com/Netflix/dispatch/files/5934884/output.txt)
* Curated logs 👇
```
Setting up database...
Do you want to load example data (WARNING: this will remove all existing database data) (y/N)?N
Running standard database migrations...
Creating dispatch_core_1 ... done
Creating dispatch_web_run ... done
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 1c3f808aa00c -> 38f0b01448ba, Adds on delete cascade behavior and renames primary and foreign keys, and sequence id for report
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "status_report_pkey" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 606, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 350, in upgrade_database
    alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 481, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 83, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 77, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 560, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/versions/38f0b01448ba_.py", line 22, in upgrade
    bind.execute("ALTER INDEX status_report_pkey RENAME TO report_pkey")
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "status_report_pkey" does not exist

[SQL: ALTER INDEX status_report_pkey RENAME TO report_pkey]
(Background on this error at: http://sqlalche.me/e/13/f405)
Cleaning up...
```

### Desktop
 - OS
    ```
    $ system_profiler SPSoftwareDataType
    
        System Software Overview:
            System Version: macOS 10.15.7 (19H512)
            Kernel Version: Darwin 19.6.0
    ```
 - Container Engine: `docker-desktop@3.1.0 (51484)` 
    ```
    $ docker --version && docker-compose --version
        Docker version 20.10.2, build 2291f61
        docker-compose version 1.27.4, build 40524192
    ```
    
### Additional Context
 This project looks awesome --looking forward to trying it out 🧪

**Comment by mvilanova** [comment]
Thanks for the report @dk0r . I'll put out a fix right now.

**Comment by mvilanova** [comment]
Ok, we have a fix for this issue in `master`, but we haven't cut a release and tagged it with `latest`. If you replace `latest` with `master` [here](https://github.com/Netflix/dispatch-docker/blob/master/docker-compose.yml#L22) it should work. Let me know if that's not the case.

**Comment by dk0r** [comment]
Resolved. Added a ✩ for the rapid **TTR**<sub>respond</sub>
Thanks @mvilanova 🙏
