### ISSUE TITLE
update incident from slack doesn't work

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#878]
**Describe the bug**
/dispatch-update-incident  from slack doesn't work, slack app works in socket mode, and I can't setup Request URL in slack App
**To Reproduce**
1. Go to slack in the incident channel 
2. Run /dispatch-update-incident 
```
ERROR:The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'app_missing_action_url'}:/usr/local/lib/python3.8/site-packages/dispatch/decorators.py:wrapper:44
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 37, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/dialogs.py", line 120, in create_update_incident_dialog
    dispatch_slack_service.open_dialog_with_user(slack_client, command["trigger_id"], dialog)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 412, in open_dialog_with_user
    return make_call(client, "dialog.open", trigger_id=trigger_id, dialog=dialog)
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 333, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 423, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 426, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 139, in make_call
    raise e
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/service.py", line 115, in make_call
    response = client.api_call(endpoint, json=kwargs)
  File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 128, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 164, in _sync_send
    return self._urllib_api_call(
  File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 292, in _urllib_api_call
    return SlackResponse(
  File "/usr/local/lib/python3.8/site-packages/slack_sdk/web/slack_response.py", line 201, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'app_missing_action_url'}
```

**Expected behavior**
expected open dialog

**Additional context**

**Comment by mvilanova** [comment]
@bender92 did you forget to set the request URL in the Interactivity & Shortcuts section in the app by any chance? See [here](https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-slack#interactivity) for instructions.

**Comment by bender92** [comment]
yep, thank you I've understood how it is working, first of all you set up request URL in the Interactivity & Shortcuts section  , and only after that enable socket mode, it was not so obvious )
