### ISSUE TITLE
Docker image crashes on start: SQLAlchemy 1.4.0 breaks SQLAlchemy-utils

### ISSUE THREAD

**Issue by jceresini** [Netflix/dispatch#945]
**Describe the bug**
After building the docker image, it fails to start with the following traceback

```
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 5, in <module>
    from dispatch.cli import entrypoint
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 15, in <module>
    from .main import *  # noqa

  File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 16, in <module>
    from .api import api_router
  File "/usr/local/lib/python3.8/site-packages/dispatch/api.py", line 6, in <module>
    from dispatch.auth.service import get_current_user
  File "/usr/local/lib/python3.8/site-packages/dispatch/auth/service.py", line 16, in <module>
    from dispatch.database import get_db
  File "/usr/local/lib/python3.8/site-packages/dispatch/database.py", line 12, in <module>
    from sqlalchemy_searchable import make_searchable
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_searchable/__init__.py", line 8, in <module>
    from sqlalchemy_utils import TSVectorType
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa

  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa

  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py)
```

**To Reproduce**
1. Build the docker image
2. Attempt to run it
3. See it fail to start with import errors

**Expected behavior**

**Additional context**
Appears to be related to https://github.com/kvesteri/sqlalchemy-utils/issues/505

**Comment by mvilanova** [comment]
Thanks for the issue report!

**Comment by mvilanova** [comment]
I should have mentioned that can replace `latest` with `master` [here](https://github.com/Netflix/dispatch-docker/blob/master/docker-compose.yml#L22) to build the core image until we cut a new release.
